services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: colight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
