// Code generated by ent, DO NOT EDIT.

package experienceusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldUserID, v))
}

// QuestionText applies equality check predicate on the "question_text" field. It's identical to QuestionTextEQ.
func QuestionText(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldQuestionText, v))
}

// CompanyName applies equality check predicate on the "company_name" field. It's identical to CompanyNameEQ.
func CompanyName(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldCompanyName, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldUsedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// QuestionTextEQ applies the EQ predicate on the "question_text" field.
func QuestionTextEQ(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldQuestionText, v))
}

// QuestionTextNEQ applies the NEQ predicate on the "question_text" field.
func QuestionTextNEQ(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNEQ(FieldQuestionText, v))
}

// QuestionTextIn applies the In predicate on the "question_text" field.
func QuestionTextIn(vs ...string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIn(FieldQuestionText, vs...))
}

// QuestionTextNotIn applies the NotIn predicate on the "question_text" field.
func QuestionTextNotIn(vs ...string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotIn(FieldQuestionText, vs...))
}

// QuestionTextGT applies the GT predicate on the "question_text" field.
func QuestionTextGT(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGT(FieldQuestionText, v))
}

// QuestionTextGTE applies the GTE predicate on the "question_text" field.
func QuestionTextGTE(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGTE(FieldQuestionText, v))
}

// QuestionTextLT applies the LT predicate on the "question_text" field.
func QuestionTextLT(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLT(FieldQuestionText, v))
}

// QuestionTextLTE applies the LTE predicate on the "question_text" field.
func QuestionTextLTE(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLTE(FieldQuestionText, v))
}

// QuestionTextContains applies the Contains predicate on the "question_text" field.
func QuestionTextContains(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldContains(FieldQuestionText, v))
}

// QuestionTextHasPrefix applies the HasPrefix predicate on the "question_text" field.
func QuestionTextHasPrefix(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldHasPrefix(FieldQuestionText, v))
}

// QuestionTextHasSuffix applies the HasSuffix predicate on the "question_text" field.
func QuestionTextHasSuffix(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldHasSuffix(FieldQuestionText, v))
}

// QuestionTextIsNil applies the IsNil predicate on the "question_text" field.
func QuestionTextIsNil() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIsNull(FieldQuestionText))
}

// QuestionTextNotNil applies the NotNil predicate on the "question_text" field.
func QuestionTextNotNil() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotNull(FieldQuestionText))
}

// QuestionTextEqualFold applies the EqualFold predicate on the "question_text" field.
func QuestionTextEqualFold(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEqualFold(FieldQuestionText, v))
}

// QuestionTextContainsFold applies the ContainsFold predicate on the "question_text" field.
func QuestionTextContainsFold(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldContainsFold(FieldQuestionText, v))
}

// CompanyNameEQ applies the EQ predicate on the "company_name" field.
func CompanyNameEQ(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldCompanyName, v))
}

// CompanyNameNEQ applies the NEQ predicate on the "company_name" field.
func CompanyNameNEQ(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNEQ(FieldCompanyName, v))
}

// CompanyNameIn applies the In predicate on the "company_name" field.
func CompanyNameIn(vs ...string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIn(FieldCompanyName, vs...))
}

// CompanyNameNotIn applies the NotIn predicate on the "company_name" field.
func CompanyNameNotIn(vs ...string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotIn(FieldCompanyName, vs...))
}

// CompanyNameGT applies the GT predicate on the "company_name" field.
func CompanyNameGT(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGT(FieldCompanyName, v))
}

// CompanyNameGTE applies the GTE predicate on the "company_name" field.
func CompanyNameGTE(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGTE(FieldCompanyName, v))
}

// CompanyNameLT applies the LT predicate on the "company_name" field.
func CompanyNameLT(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLT(FieldCompanyName, v))
}

// CompanyNameLTE applies the LTE predicate on the "company_name" field.
func CompanyNameLTE(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLTE(FieldCompanyName, v))
}

// CompanyNameContains applies the Contains predicate on the "company_name" field.
func CompanyNameContains(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldContains(FieldCompanyName, v))
}

// CompanyNameHasPrefix applies the HasPrefix predicate on the "company_name" field.
func CompanyNameHasPrefix(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldHasPrefix(FieldCompanyName, v))
}

// CompanyNameHasSuffix applies the HasSuffix predicate on the "company_name" field.
func CompanyNameHasSuffix(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldHasSuffix(FieldCompanyName, v))
}

// CompanyNameIsNil applies the IsNil predicate on the "company_name" field.
func CompanyNameIsNil() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIsNull(FieldCompanyName))
}

// CompanyNameNotNil applies the NotNil predicate on the "company_name" field.
func CompanyNameNotNil() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotNull(FieldCompanyName))
}

// CompanyNameEqualFold applies the EqualFold predicate on the "company_name" field.
func CompanyNameEqualFold(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEqualFold(FieldCompanyName, v))
}

// CompanyNameContainsFold applies the ContainsFold predicate on the "company_name" field.
func CompanyNameContainsFold(v string) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldContainsFold(FieldCompanyName, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.FieldLTE(FieldUsedAt, v))
}

// HasExperience applies the HasEdge predicate on the "experience" edge.
func HasExperience() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExperienceTable, ExperienceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperienceWith applies the HasEdge predicate on the "experience" edge with a given conditions (other predicates).
func HasExperienceWith(preds ...predicate.Experience) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := newExperienceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.UserProfile) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCoverLetter applies the HasEdge predicate on the "cover_letter" edge.
func HasCoverLetter() predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CoverLetterTable, CoverLetterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoverLetterWith applies the HasEdge predicate on the "cover_letter" edge with a given conditions (other predicates).
func HasCoverLetterWith(preds ...predicate.CoverLetter) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(func(s *sql.Selector) {
		step := newCoverLetterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExperienceUsage) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExperienceUsage) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExperienceUsage) predicate.ExperienceUsage {
	return predicate.ExperienceUsage(sql.NotPredicates(p))
}
