// Code generated by ent, DO NOT EDIT.

package userprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the userprofile type in the database.
	Label = "user_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldTargetJob holds the string denoting the target_job field in the database.
	FieldTargetJob = "target_job"
	// FieldTargetIndustry holds the string denoting the target_industry field in the database.
	FieldTargetIndustry = "target_industry"
	// FieldEducationLevel holds the string denoting the education_level field in the database.
	FieldEducationLevel = "education_level"
	// FieldGraduationYear holds the string denoting the graduation_year field in the database.
	FieldGraduationYear = "graduation_year"
	// FieldExperienceYears holds the string denoting the experience_years field in the database.
	FieldExperienceYears = "experience_years"
	// FieldOnboardingCompleted holds the string denoting the onboarding_completed field in the database.
	FieldOnboardingCompleted = "onboarding_completed"
	// EdgeExperiences holds the string denoting the experiences edge name in mutations.
	EdgeExperiences = "experiences"
	// EdgeApplications holds the string denoting the applications edge name in mutations.
	EdgeApplications = "applications"
	// EdgeCompanyAnalyses holds the string denoting the company_analyses edge name in mutations.
	EdgeCompanyAnalyses = "company_analyses"
	// EdgeCoverLetters holds the string denoting the cover_letters edge name in mutations.
	EdgeCoverLetters = "cover_letters"
	// EdgeCoachingSessions holds the string denoting the coaching_sessions edge name in mutations.
	EdgeCoachingSessions = "coaching_sessions"
	// EdgeExperienceUsages holds the string denoting the experience_usages edge name in mutations.
	EdgeExperienceUsages = "experience_usages"
	// Table holds the table name of the userprofile in the database.
	Table = "user_profiles"
	// ExperiencesTable is the table that holds the experiences relation/edge.
	ExperiencesTable = "experiences"
	// ExperiencesInverseTable is the table name for the Experience entity.
	// It exists in this package in order to avoid circular dependency with the "experience" package.
	ExperiencesInverseTable = "experiences"
	// ExperiencesColumn is the table column denoting the experiences relation/edge.
	ExperiencesColumn = "user_id"
	// ApplicationsTable is the table that holds the applications relation/edge.
	ApplicationsTable = "applications"
	// ApplicationsInverseTable is the table name for the Application entity.
	// It exists in this package in order to avoid circular dependency with the "application" package.
	ApplicationsInverseTable = "applications"
	// ApplicationsColumn is the table column denoting the applications relation/edge.
	ApplicationsColumn = "user_id"
	// CompanyAnalysesTable is the table that holds the company_analyses relation/edge.
	CompanyAnalysesTable = "company_analyses"
	// CompanyAnalysesInverseTable is the table name for the CompanyAnalysis entity.
	// It exists in this package in order to avoid circular dependency with the "companyanalysis" package.
	CompanyAnalysesInverseTable = "company_analyses"
	// CompanyAnalysesColumn is the table column denoting the company_analyses relation/edge.
	CompanyAnalysesColumn = "user_id"
	// CoverLettersTable is the table that holds the cover_letters relation/edge.
	CoverLettersTable = "cover_letters"
	// CoverLettersInverseTable is the table name for the CoverLetter entity.
	// It exists in this package in order to avoid circular dependency with the "coverletter" package.
	CoverLettersInverseTable = "cover_letters"
	// CoverLettersColumn is the table column denoting the cover_letters relation/edge.
	CoverLettersColumn = "user_id"
	// CoachingSessionsTable is the table that holds the coaching_sessions relation/edge.
	CoachingSessionsTable = "coaching_sessions"
	// CoachingSessionsInverseTable is the table name for the CoachingSession entity.
	// It exists in this package in order to avoid circular dependency with the "coachingsession" package.
	CoachingSessionsInverseTable = "coaching_sessions"
	// CoachingSessionsColumn is the table column denoting the coaching_sessions relation/edge.
	CoachingSessionsColumn = "user_id"
	// ExperienceUsagesTable is the table that holds the experience_usages relation/edge.
	ExperienceUsagesTable = "experience_usages"
	// ExperienceUsagesInverseTable is the table name for the ExperienceUsage entity.
	// It exists in this package in order to avoid circular dependency with the "experienceusage" package.
	ExperienceUsagesInverseTable = "experience_usages"
	// ExperienceUsagesColumn is the table column denoting the experience_usages relation/edge.
	ExperienceUsagesColumn = "user_id"
)

// Columns holds all SQL columns for userprofile fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldNickname,
	FieldTargetJob,
	FieldTargetIndustry,
	FieldEducationLevel,
	FieldGraduationYear,
	FieldExperienceYears,
	FieldOnboardingCompleted,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// TargetJobValidator is a validator for the "target_job" field. It is called by the builders before save.
	TargetJobValidator func(string) error
	// TargetIndustryValidator is a validator for the "target_industry" field. It is called by the builders before save.
	TargetIndustryValidator func(string) error
	// EducationLevelValidator is a validator for the "education_level" field. It is called by the builders before save.
	EducationLevelValidator func(string) error
	// DefaultExperienceYears holds the default value on creation for the "experience_years" field.
	DefaultExperienceYears int
	// DefaultOnboardingCompleted holds the default value on creation for the "onboarding_completed" field.
	DefaultOnboardingCompleted bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UserProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByTargetJob orders the results by the target_job field.
func ByTargetJob(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetJob, opts...).ToFunc()
}

// ByTargetIndustry orders the results by the target_industry field.
func ByTargetIndustry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetIndustry, opts...).ToFunc()
}

// ByEducationLevel orders the results by the education_level field.
func ByEducationLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEducationLevel, opts...).ToFunc()
}

// ByGraduationYear orders the results by the graduation_year field.
func ByGraduationYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGraduationYear, opts...).ToFunc()
}

// ByExperienceYears orders the results by the experience_years field.
func ByExperienceYears(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExperienceYears, opts...).ToFunc()
}

// ByOnboardingCompleted orders the results by the onboarding_completed field.
func ByOnboardingCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnboardingCompleted, opts...).ToFunc()
}

// ByExperiencesCount orders the results by experiences count.
func ByExperiencesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExperiencesStep(), opts...)
	}
}

// ByExperiences orders the results by experiences terms.
func ByExperiences(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExperiencesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByApplicationsCount orders the results by applications count.
func ByApplicationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newApplicationsStep(), opts...)
	}
}

// ByApplications orders the results by applications terms.
func ByApplications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApplicationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCompanyAnalysesCount orders the results by company_analyses count.
func ByCompanyAnalysesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCompanyAnalysesStep(), opts...)
	}
}

// ByCompanyAnalyses orders the results by company_analyses terms.
func ByCompanyAnalyses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompanyAnalysesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCoverLettersCount orders the results by cover_letters count.
func ByCoverLettersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCoverLettersStep(), opts...)
	}
}

// ByCoverLetters orders the results by cover_letters terms.
func ByCoverLetters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCoverLettersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCoachingSessionsCount orders the results by coaching_sessions count.
func ByCoachingSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCoachingSessionsStep(), opts...)
	}
}

// ByCoachingSessions orders the results by coaching_sessions terms.
func ByCoachingSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCoachingSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExperienceUsagesCount orders the results by experience_usages count.
func ByExperienceUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExperienceUsagesStep(), opts...)
	}
}

// ByExperienceUsages orders the results by experience_usages terms.
func ByExperienceUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExperienceUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newExperiencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExperiencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExperiencesTable, ExperiencesColumn),
	)
}
func newApplicationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApplicationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ApplicationsTable, ApplicationsColumn),
	)
}
func newCompanyAnalysesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompanyAnalysesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CompanyAnalysesTable, CompanyAnalysesColumn),
	)
}
func newCoverLettersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CoverLettersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CoverLettersTable, CoverLettersColumn),
	)
}
func newCoachingSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CoachingSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CoachingSessionsTable, CoachingSessionsColumn),
	)
}
func newExperienceUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExperienceUsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExperienceUsagesTable, ExperienceUsagesColumn),
	)
}
