// Code generated by ent, DO NOT EDIT.

package userprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPasswordHash, v))
}

// NaverID applies equality check predicate on the "naver_id" field. It's identical to NaverIDEQ.
func NaverID(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldNaverID, v))
}

// EmailVerified applies equality check predicate on the "email_verified" field. It's identical to EmailVerifiedEQ.
func EmailVerified(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldEmailVerified, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldLastLoginAt, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldNickname, v))
}

// TargetJob applies equality check predicate on the "target_job" field. It's identical to TargetJobEQ.
func TargetJob(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldTargetJob, v))
}

// TargetIndustry applies equality check predicate on the "target_industry" field. It's identical to TargetIndustryEQ.
func TargetIndustry(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldTargetIndustry, v))
}

// EducationLevel applies equality check predicate on the "education_level" field. It's identical to EducationLevelEQ.
func EducationLevel(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldEducationLevel, v))
}

// GraduationYear applies equality check predicate on the "graduation_year" field. It's identical to GraduationYearEQ.
func GraduationYear(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldGraduationYear, v))
}

// ExperienceYears applies equality check predicate on the "experience_years" field. It's identical to ExperienceYearsEQ.
func ExperienceYears(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldExperienceYears, v))
}

// OnboardingCompleted applies equality check predicate on the "onboarding_completed" field. It's identical to OnboardingCompletedEQ.
func OnboardingCompleted(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldOnboardingCompleted, v))
}

// Suspended applies equality check predicate on the "suspended" field. It's identical to SuspendedEQ.
func Suspended(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSuspended, v))
}

// SuspendedAt applies equality check predicate on the "suspended_at" field. It's identical to SuspendedAtEQ.
func SuspendedAt(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSuspendedAt, v))
}

// SuspendedReason applies equality check predicate on the "suspended_reason" field. It's identical to SuspendedReasonEQ.
func SuspendedReason(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSuspendedReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashIsNil applies the IsNil predicate on the "password_hash" field.
func PasswordHashIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldPasswordHash))
}

// PasswordHashNotNil applies the NotNil predicate on the "password_hash" field.
func PasswordHashNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldPasswordHash))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldPasswordHash, v))
}

// NaverIDEQ applies the EQ predicate on the "naver_id" field.
func NaverIDEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldNaverID, v))
}

// NaverIDNEQ applies the NEQ predicate on the "naver_id" field.
func NaverIDNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldNaverID, v))
}

// NaverIDIn applies the In predicate on the "naver_id" field.
func NaverIDIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldNaverID, vs...))
}

// NaverIDNotIn applies the NotIn predicate on the "naver_id" field.
func NaverIDNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldNaverID, vs...))
}

// NaverIDGT applies the GT predicate on the "naver_id" field.
func NaverIDGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldNaverID, v))
}

// NaverIDGTE applies the GTE predicate on the "naver_id" field.
func NaverIDGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldNaverID, v))
}

// NaverIDLT applies the LT predicate on the "naver_id" field.
func NaverIDLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldNaverID, v))
}

// NaverIDLTE applies the LTE predicate on the "naver_id" field.
func NaverIDLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldNaverID, v))
}

// NaverIDContains applies the Contains predicate on the "naver_id" field.
func NaverIDContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldNaverID, v))
}

// NaverIDHasPrefix applies the HasPrefix predicate on the "naver_id" field.
func NaverIDHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldNaverID, v))
}

// NaverIDHasSuffix applies the HasSuffix predicate on the "naver_id" field.
func NaverIDHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldNaverID, v))
}

// NaverIDIsNil applies the IsNil predicate on the "naver_id" field.
func NaverIDIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldNaverID))
}

// NaverIDNotNil applies the NotNil predicate on the "naver_id" field.
func NaverIDNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldNaverID))
}

// NaverIDEqualFold applies the EqualFold predicate on the "naver_id" field.
func NaverIDEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldNaverID, v))
}

// NaverIDContainsFold applies the ContainsFold predicate on the "naver_id" field.
func NaverIDContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldNaverID, v))
}

// AuthProviderEQ applies the EQ predicate on the "auth_provider" field.
func AuthProviderEQ(v AuthProvider) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldAuthProvider, v))
}

// AuthProviderNEQ applies the NEQ predicate on the "auth_provider" field.
func AuthProviderNEQ(v AuthProvider) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldAuthProvider, v))
}

// AuthProviderIn applies the In predicate on the "auth_provider" field.
func AuthProviderIn(vs ...AuthProvider) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldAuthProvider, vs...))
}

// AuthProviderNotIn applies the NotIn predicate on the "auth_provider" field.
func AuthProviderNotIn(vs ...AuthProvider) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldAuthProvider, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldRole, vs...))
}

// EmailVerifiedEQ applies the EQ predicate on the "email_verified" field.
func EmailVerifiedEQ(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldEmailVerified, v))
}

// EmailVerifiedNEQ applies the NEQ predicate on the "email_verified" field.
func EmailVerifiedNEQ(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldEmailVerified, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldLastLoginAt))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameIsNil applies the IsNil predicate on the "nickname" field.
func NicknameIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldNickname))
}

// NicknameNotNil applies the NotNil predicate on the "nickname" field.
func NicknameNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldNickname))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldNickname, v))
}

// TargetJobEQ applies the EQ predicate on the "target_job" field.
func TargetJobEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldTargetJob, v))
}

// TargetJobNEQ applies the NEQ predicate on the "target_job" field.
func TargetJobNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldTargetJob, v))
}

// TargetJobIn applies the In predicate on the "target_job" field.
func TargetJobIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldTargetJob, vs...))
}

// TargetJobNotIn applies the NotIn predicate on the "target_job" field.
func TargetJobNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldTargetJob, vs...))
}

// TargetJobGT applies the GT predicate on the "target_job" field.
func TargetJobGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldTargetJob, v))
}

// TargetJobGTE applies the GTE predicate on the "target_job" field.
func TargetJobGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldTargetJob, v))
}

// TargetJobLT applies the LT predicate on the "target_job" field.
func TargetJobLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldTargetJob, v))
}

// TargetJobLTE applies the LTE predicate on the "target_job" field.
func TargetJobLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldTargetJob, v))
}

// TargetJobContains applies the Contains predicate on the "target_job" field.
func TargetJobContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldTargetJob, v))
}

// TargetJobHasPrefix applies the HasPrefix predicate on the "target_job" field.
func TargetJobHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldTargetJob, v))
}

// TargetJobHasSuffix applies the HasSuffix predicate on the "target_job" field.
func TargetJobHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldTargetJob, v))
}

// TargetJobIsNil applies the IsNil predicate on the "target_job" field.
func TargetJobIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldTargetJob))
}

// TargetJobNotNil applies the NotNil predicate on the "target_job" field.
func TargetJobNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldTargetJob))
}

// TargetJobEqualFold applies the EqualFold predicate on the "target_job" field.
func TargetJobEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldTargetJob, v))
}

// TargetJobContainsFold applies the ContainsFold predicate on the "target_job" field.
func TargetJobContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldTargetJob, v))
}

// TargetIndustryEQ applies the EQ predicate on the "target_industry" field.
func TargetIndustryEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldTargetIndustry, v))
}

// TargetIndustryNEQ applies the NEQ predicate on the "target_industry" field.
func TargetIndustryNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldTargetIndustry, v))
}

// TargetIndustryIn applies the In predicate on the "target_industry" field.
func TargetIndustryIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldTargetIndustry, vs...))
}

// TargetIndustryNotIn applies the NotIn predicate on the "target_industry" field.
func TargetIndustryNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldTargetIndustry, vs...))
}

// TargetIndustryGT applies the GT predicate on the "target_industry" field.
func TargetIndustryGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldTargetIndustry, v))
}

// TargetIndustryGTE applies the GTE predicate on the "target_industry" field.
func TargetIndustryGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldTargetIndustry, v))
}

// TargetIndustryLT applies the LT predicate on the "target_industry" field.
func TargetIndustryLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldTargetIndustry, v))
}

// TargetIndustryLTE applies the LTE predicate on the "target_industry" field.
func TargetIndustryLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldTargetIndustry, v))
}

// TargetIndustryContains applies the Contains predicate on the "target_industry" field.
func TargetIndustryContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldTargetIndustry, v))
}

// TargetIndustryHasPrefix applies the HasPrefix predicate on the "target_industry" field.
func TargetIndustryHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldTargetIndustry, v))
}

// TargetIndustryHasSuffix applies the HasSuffix predicate on the "target_industry" field.
func TargetIndustryHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldTargetIndustry, v))
}

// TargetIndustryIsNil applies the IsNil predicate on the "target_industry" field.
func TargetIndustryIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldTargetIndustry))
}

// TargetIndustryNotNil applies the NotNil predicate on the "target_industry" field.
func TargetIndustryNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldTargetIndustry))
}

// TargetIndustryEqualFold applies the EqualFold predicate on the "target_industry" field.
func TargetIndustryEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldTargetIndustry, v))
}

// TargetIndustryContainsFold applies the ContainsFold predicate on the "target_industry" field.
func TargetIndustryContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldTargetIndustry, v))
}

// EducationLevelEQ applies the EQ predicate on the "education_level" field.
func EducationLevelEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldEducationLevel, v))
}

// EducationLevelNEQ applies the NEQ predicate on the "education_level" field.
func EducationLevelNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldEducationLevel, v))
}

// EducationLevelIn applies the In predicate on the "education_level" field.
func EducationLevelIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldEducationLevel, vs...))
}

// EducationLevelNotIn applies the NotIn predicate on the "education_level" field.
func EducationLevelNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldEducationLevel, vs...))
}

// EducationLevelGT applies the GT predicate on the "education_level" field.
func EducationLevelGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldEducationLevel, v))
}

// EducationLevelGTE applies the GTE predicate on the "education_level" field.
func EducationLevelGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldEducationLevel, v))
}

// EducationLevelLT applies the LT predicate on the "education_level" field.
func EducationLevelLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldEducationLevel, v))
}

// EducationLevelLTE applies the LTE predicate on the "education_level" field.
func EducationLevelLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldEducationLevel, v))
}

// EducationLevelContains applies the Contains predicate on the "education_level" field.
func EducationLevelContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldEducationLevel, v))
}

// EducationLevelHasPrefix applies the HasPrefix predicate on the "education_level" field.
func EducationLevelHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldEducationLevel, v))
}

// EducationLevelHasSuffix applies the HasSuffix predicate on the "education_level" field.
func EducationLevelHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldEducationLevel, v))
}

// EducationLevelIsNil applies the IsNil predicate on the "education_level" field.
func EducationLevelIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldEducationLevel))
}

// EducationLevelNotNil applies the NotNil predicate on the "education_level" field.
func EducationLevelNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldEducationLevel))
}

// EducationLevelEqualFold applies the EqualFold predicate on the "education_level" field.
func EducationLevelEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldEducationLevel, v))
}

// EducationLevelContainsFold applies the ContainsFold predicate on the "education_level" field.
func EducationLevelContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldEducationLevel, v))
}

// GraduationYearEQ applies the EQ predicate on the "graduation_year" field.
func GraduationYearEQ(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldGraduationYear, v))
}

// GraduationYearNEQ applies the NEQ predicate on the "graduation_year" field.
func GraduationYearNEQ(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldGraduationYear, v))
}

// GraduationYearIn applies the In predicate on the "graduation_year" field.
func GraduationYearIn(vs ...int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldGraduationYear, vs...))
}

// GraduationYearNotIn applies the NotIn predicate on the "graduation_year" field.
func GraduationYearNotIn(vs ...int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldGraduationYear, vs...))
}

// GraduationYearGT applies the GT predicate on the "graduation_year" field.
func GraduationYearGT(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldGraduationYear, v))
}

// GraduationYearGTE applies the GTE predicate on the "graduation_year" field.
func GraduationYearGTE(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldGraduationYear, v))
}

// GraduationYearLT applies the LT predicate on the "graduation_year" field.
func GraduationYearLT(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldGraduationYear, v))
}

// GraduationYearLTE applies the LTE predicate on the "graduation_year" field.
func GraduationYearLTE(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldGraduationYear, v))
}

// GraduationYearIsNil applies the IsNil predicate on the "graduation_year" field.
func GraduationYearIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldGraduationYear))
}

// GraduationYearNotNil applies the NotNil predicate on the "graduation_year" field.
func GraduationYearNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldGraduationYear))
}

// ExperienceYearsEQ applies the EQ predicate on the "experience_years" field.
func ExperienceYearsEQ(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldExperienceYears, v))
}

// ExperienceYearsNEQ applies the NEQ predicate on the "experience_years" field.
func ExperienceYearsNEQ(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldExperienceYears, v))
}

// ExperienceYearsIn applies the In predicate on the "experience_years" field.
func ExperienceYearsIn(vs ...int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldExperienceYears, vs...))
}

// ExperienceYearsNotIn applies the NotIn predicate on the "experience_years" field.
func ExperienceYearsNotIn(vs ...int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldExperienceYears, vs...))
}

// ExperienceYearsGT applies the GT predicate on the "experience_years" field.
func ExperienceYearsGT(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldExperienceYears, v))
}

// ExperienceYearsGTE applies the GTE predicate on the "experience_years" field.
func ExperienceYearsGTE(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldExperienceYears, v))
}

// ExperienceYearsLT applies the LT predicate on the "experience_years" field.
func ExperienceYearsLT(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldExperienceYears, v))
}

// ExperienceYearsLTE applies the LTE predicate on the "experience_years" field.
func ExperienceYearsLTE(v int) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldExperienceYears, v))
}

// OnboardingCompletedEQ applies the EQ predicate on the "onboarding_completed" field.
func OnboardingCompletedEQ(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldOnboardingCompleted, v))
}

// OnboardingCompletedNEQ applies the NEQ predicate on the "onboarding_completed" field.
func OnboardingCompletedNEQ(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldOnboardingCompleted, v))
}

// PlanEQ applies the EQ predicate on the "plan" field.
func PlanEQ(v Plan) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPlan, v))
}

// PlanNEQ applies the NEQ predicate on the "plan" field.
func PlanNEQ(v Plan) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldPlan, v))
}

// PlanIn applies the In predicate on the "plan" field.
func PlanIn(vs ...Plan) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldPlan, vs...))
}

// PlanNotIn applies the NotIn predicate on the "plan" field.
func PlanNotIn(vs ...Plan) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldPlan, vs...))
}

// SuspendedEQ applies the EQ predicate on the "suspended" field.
func SuspendedEQ(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSuspended, v))
}

// SuspendedNEQ applies the NEQ predicate on the "suspended" field.
func SuspendedNEQ(v bool) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldSuspended, v))
}

// SuspendedAtEQ applies the EQ predicate on the "suspended_at" field.
func SuspendedAtEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSuspendedAt, v))
}

// SuspendedAtNEQ applies the NEQ predicate on the "suspended_at" field.
func SuspendedAtNEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldSuspendedAt, v))
}

// SuspendedAtIn applies the In predicate on the "suspended_at" field.
func SuspendedAtIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldSuspendedAt, vs...))
}

// SuspendedAtNotIn applies the NotIn predicate on the "suspended_at" field.
func SuspendedAtNotIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldSuspendedAt, vs...))
}

// SuspendedAtGT applies the GT predicate on the "suspended_at" field.
func SuspendedAtGT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldSuspendedAt, v))
}

// SuspendedAtGTE applies the GTE predicate on the "suspended_at" field.
func SuspendedAtGTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldSuspendedAt, v))
}

// SuspendedAtLT applies the LT predicate on the "suspended_at" field.
func SuspendedAtLT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldSuspendedAt, v))
}

// SuspendedAtLTE applies the LTE predicate on the "suspended_at" field.
func SuspendedAtLTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldSuspendedAt, v))
}

// SuspendedAtIsNil applies the IsNil predicate on the "suspended_at" field.
func SuspendedAtIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldSuspendedAt))
}

// SuspendedAtNotNil applies the NotNil predicate on the "suspended_at" field.
func SuspendedAtNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldSuspendedAt))
}

// SuspendedReasonEQ applies the EQ predicate on the "suspended_reason" field.
func SuspendedReasonEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSuspendedReason, v))
}

// SuspendedReasonNEQ applies the NEQ predicate on the "suspended_reason" field.
func SuspendedReasonNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldSuspendedReason, v))
}

// SuspendedReasonIn applies the In predicate on the "suspended_reason" field.
func SuspendedReasonIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldSuspendedReason, vs...))
}

// SuspendedReasonNotIn applies the NotIn predicate on the "suspended_reason" field.
func SuspendedReasonNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldSuspendedReason, vs...))
}

// SuspendedReasonGT applies the GT predicate on the "suspended_reason" field.
func SuspendedReasonGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldSuspendedReason, v))
}

// SuspendedReasonGTE applies the GTE predicate on the "suspended_reason" field.
func SuspendedReasonGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldSuspendedReason, v))
}

// SuspendedReasonLT applies the LT predicate on the "suspended_reason" field.
func SuspendedReasonLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldSuspendedReason, v))
}

// SuspendedReasonLTE applies the LTE predicate on the "suspended_reason" field.
func SuspendedReasonLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldSuspendedReason, v))
}

// SuspendedReasonContains applies the Contains predicate on the "suspended_reason" field.
func SuspendedReasonContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldSuspendedReason, v))
}

// SuspendedReasonHasPrefix applies the HasPrefix predicate on the "suspended_reason" field.
func SuspendedReasonHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldSuspendedReason, v))
}

// SuspendedReasonHasSuffix applies the HasSuffix predicate on the "suspended_reason" field.
func SuspendedReasonHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldSuspendedReason, v))
}

// SuspendedReasonIsNil applies the IsNil predicate on the "suspended_reason" field.
func SuspendedReasonIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldSuspendedReason))
}

// SuspendedReasonNotNil applies the NotNil predicate on the "suspended_reason" field.
func SuspendedReasonNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldSuspendedReason))
}

// SuspendedReasonEqualFold applies the EqualFold predicate on the "suspended_reason" field.
func SuspendedReasonEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldSuspendedReason, v))
}

// SuspendedReasonContainsFold applies the ContainsFold predicate on the "suspended_reason" field.
func SuspendedReasonContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldSuspendedReason, v))
}

// HasExperiences applies the HasEdge predicate on the "experiences" edge.
func HasExperiences() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperiencesTable, ExperiencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperiencesWith applies the HasEdge predicate on the "experiences" edge with a given conditions (other predicates).
func HasExperiencesWith(preds ...predicate.Experience) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newExperiencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplications applies the HasEdge predicate on the "applications" edge.
func HasApplications() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ApplicationsTable, ApplicationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationsWith applies the HasEdge predicate on the "applications" edge with a given conditions (other predicates).
func HasApplicationsWith(preds ...predicate.Application) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newApplicationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCompanyAnalyses applies the HasEdge predicate on the "company_analyses" edge.
func HasCompanyAnalyses() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CompanyAnalysesTable, CompanyAnalysesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyAnalysesWith applies the HasEdge predicate on the "company_analyses" edge with a given conditions (other predicates).
func HasCompanyAnalysesWith(preds ...predicate.CompanyAnalysis) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newCompanyAnalysesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCoverLetters applies the HasEdge predicate on the "cover_letters" edge.
func HasCoverLetters() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CoverLettersTable, CoverLettersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoverLettersWith applies the HasEdge predicate on the "cover_letters" edge with a given conditions (other predicates).
func HasCoverLettersWith(preds ...predicate.CoverLetter) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newCoverLettersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCoachingSessions applies the HasEdge predicate on the "coaching_sessions" edge.
func HasCoachingSessions() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CoachingSessionsTable, CoachingSessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoachingSessionsWith applies the HasEdge predicate on the "coaching_sessions" edge with a given conditions (other predicates).
func HasCoachingSessionsWith(preds ...predicate.CoachingSession) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newCoachingSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperienceUsages applies the HasEdge predicate on the "experience_usages" edge.
func HasExperienceUsages() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperienceUsagesTable, ExperienceUsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperienceUsagesWith applies the HasEdge predicate on the "experience_usages" edge with a given conditions (other predicates).
func HasExperienceUsagesWith(preds ...predicate.ExperienceUsage) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newExperienceUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFeedbacks applies the HasEdge predicate on the "feedbacks" edge.
func HasFeedbacks() predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FeedbacksTable, FeedbacksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFeedbacksWith applies the HasEdge predicate on the "feedbacks" edge with a given conditions (other predicates).
func HasFeedbacksWith(preds ...predicate.Feedback) predicate.UserProfile {
	return predicate.UserProfile(func(s *sql.Selector) {
		step := newFeedbacksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserProfile) predicate.UserProfile {
	return predicate.UserProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserProfile) predicate.UserProfile {
	return predicate.UserProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserProfile) predicate.UserProfile {
	return predicate.UserProfile(sql.NotPredicates(p))
}
