// Code generated by ent, DO NOT EDIT.

package questionpattern

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldCreatedAt, v))
}

// PatternType applies equality check predicate on the "pattern_type" field. It's identical to PatternTypeEQ.
func PatternType(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldPatternType, v))
}

// PatternName applies equality check predicate on the "pattern_name" field. It's identical to PatternNameEQ.
func PatternName(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldPatternName, v))
}

// DetectionRegex applies equality check predicate on the "detection_regex" field. It's identical to DetectionRegexEQ.
func DetectionRegex(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldDetectionRegex, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldDisplayOrder, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLTE(FieldCreatedAt, v))
}

// PatternTypeEQ applies the EQ predicate on the "pattern_type" field.
func PatternTypeEQ(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldPatternType, v))
}

// PatternTypeNEQ applies the NEQ predicate on the "pattern_type" field.
func PatternTypeNEQ(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldPatternType, v))
}

// PatternTypeIn applies the In predicate on the "pattern_type" field.
func PatternTypeIn(vs ...string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIn(FieldPatternType, vs...))
}

// PatternTypeNotIn applies the NotIn predicate on the "pattern_type" field.
func PatternTypeNotIn(vs ...string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotIn(FieldPatternType, vs...))
}

// PatternTypeGT applies the GT predicate on the "pattern_type" field.
func PatternTypeGT(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGT(FieldPatternType, v))
}

// PatternTypeGTE applies the GTE predicate on the "pattern_type" field.
func PatternTypeGTE(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGTE(FieldPatternType, v))
}

// PatternTypeLT applies the LT predicate on the "pattern_type" field.
func PatternTypeLT(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLT(FieldPatternType, v))
}

// PatternTypeLTE applies the LTE predicate on the "pattern_type" field.
func PatternTypeLTE(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLTE(FieldPatternType, v))
}

// PatternTypeContains applies the Contains predicate on the "pattern_type" field.
func PatternTypeContains(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldContains(FieldPatternType, v))
}

// PatternTypeHasPrefix applies the HasPrefix predicate on the "pattern_type" field.
func PatternTypeHasPrefix(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldHasPrefix(FieldPatternType, v))
}

// PatternTypeHasSuffix applies the HasSuffix predicate on the "pattern_type" field.
func PatternTypeHasSuffix(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldHasSuffix(FieldPatternType, v))
}

// PatternTypeEqualFold applies the EqualFold predicate on the "pattern_type" field.
func PatternTypeEqualFold(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEqualFold(FieldPatternType, v))
}

// PatternTypeContainsFold applies the ContainsFold predicate on the "pattern_type" field.
func PatternTypeContainsFold(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldContainsFold(FieldPatternType, v))
}

// PatternNameEQ applies the EQ predicate on the "pattern_name" field.
func PatternNameEQ(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldPatternName, v))
}

// PatternNameNEQ applies the NEQ predicate on the "pattern_name" field.
func PatternNameNEQ(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldPatternName, v))
}

// PatternNameIn applies the In predicate on the "pattern_name" field.
func PatternNameIn(vs ...string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIn(FieldPatternName, vs...))
}

// PatternNameNotIn applies the NotIn predicate on the "pattern_name" field.
func PatternNameNotIn(vs ...string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotIn(FieldPatternName, vs...))
}

// PatternNameGT applies the GT predicate on the "pattern_name" field.
func PatternNameGT(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGT(FieldPatternName, v))
}

// PatternNameGTE applies the GTE predicate on the "pattern_name" field.
func PatternNameGTE(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGTE(FieldPatternName, v))
}

// PatternNameLT applies the LT predicate on the "pattern_name" field.
func PatternNameLT(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLT(FieldPatternName, v))
}

// PatternNameLTE applies the LTE predicate on the "pattern_name" field.
func PatternNameLTE(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLTE(FieldPatternName, v))
}

// PatternNameContains applies the Contains predicate on the "pattern_name" field.
func PatternNameContains(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldContains(FieldPatternName, v))
}

// PatternNameHasPrefix applies the HasPrefix predicate on the "pattern_name" field.
func PatternNameHasPrefix(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldHasPrefix(FieldPatternName, v))
}

// PatternNameHasSuffix applies the HasSuffix predicate on the "pattern_name" field.
func PatternNameHasSuffix(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldHasSuffix(FieldPatternName, v))
}

// PatternNameEqualFold applies the EqualFold predicate on the "pattern_name" field.
func PatternNameEqualFold(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEqualFold(FieldPatternName, v))
}

// PatternNameContainsFold applies the ContainsFold predicate on the "pattern_name" field.
func PatternNameContainsFold(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldContainsFold(FieldPatternName, v))
}

// DetectionKeywordsIsNil applies the IsNil predicate on the "detection_keywords" field.
func DetectionKeywordsIsNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIsNull(FieldDetectionKeywords))
}

// DetectionKeywordsNotNil applies the NotNil predicate on the "detection_keywords" field.
func DetectionKeywordsNotNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotNull(FieldDetectionKeywords))
}

// DetectionRegexEQ applies the EQ predicate on the "detection_regex" field.
func DetectionRegexEQ(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldDetectionRegex, v))
}

// DetectionRegexNEQ applies the NEQ predicate on the "detection_regex" field.
func DetectionRegexNEQ(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldDetectionRegex, v))
}

// DetectionRegexIn applies the In predicate on the "detection_regex" field.
func DetectionRegexIn(vs ...string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIn(FieldDetectionRegex, vs...))
}

// DetectionRegexNotIn applies the NotIn predicate on the "detection_regex" field.
func DetectionRegexNotIn(vs ...string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotIn(FieldDetectionRegex, vs...))
}

// DetectionRegexGT applies the GT predicate on the "detection_regex" field.
func DetectionRegexGT(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGT(FieldDetectionRegex, v))
}

// DetectionRegexGTE applies the GTE predicate on the "detection_regex" field.
func DetectionRegexGTE(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGTE(FieldDetectionRegex, v))
}

// DetectionRegexLT applies the LT predicate on the "detection_regex" field.
func DetectionRegexLT(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLT(FieldDetectionRegex, v))
}

// DetectionRegexLTE applies the LTE predicate on the "detection_regex" field.
func DetectionRegexLTE(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLTE(FieldDetectionRegex, v))
}

// DetectionRegexContains applies the Contains predicate on the "detection_regex" field.
func DetectionRegexContains(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldContains(FieldDetectionRegex, v))
}

// DetectionRegexHasPrefix applies the HasPrefix predicate on the "detection_regex" field.
func DetectionRegexHasPrefix(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldHasPrefix(FieldDetectionRegex, v))
}

// DetectionRegexHasSuffix applies the HasSuffix predicate on the "detection_regex" field.
func DetectionRegexHasSuffix(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldHasSuffix(FieldDetectionRegex, v))
}

// DetectionRegexIsNil applies the IsNil predicate on the "detection_regex" field.
func DetectionRegexIsNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIsNull(FieldDetectionRegex))
}

// DetectionRegexNotNil applies the NotNil predicate on the "detection_regex" field.
func DetectionRegexNotNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotNull(FieldDetectionRegex))
}

// DetectionRegexEqualFold applies the EqualFold predicate on the "detection_regex" field.
func DetectionRegexEqualFold(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEqualFold(FieldDetectionRegex, v))
}

// DetectionRegexContainsFold applies the ContainsFold predicate on the "detection_regex" field.
func DetectionRegexContainsFold(v string) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldContainsFold(FieldDetectionRegex, v))
}

// PrimaryWeaponsIsNil applies the IsNil predicate on the "primary_weapons" field.
func PrimaryWeaponsIsNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIsNull(FieldPrimaryWeapons))
}

// PrimaryWeaponsNotNil applies the NotNil predicate on the "primary_weapons" field.
func PrimaryWeaponsNotNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotNull(FieldPrimaryWeapons))
}

// SecondaryWeaponsIsNil applies the IsNil predicate on the "secondary_weapons" field.
func SecondaryWeaponsIsNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIsNull(FieldSecondaryWeapons))
}

// SecondaryWeaponsNotNil applies the NotNil predicate on the "secondary_weapons" field.
func SecondaryWeaponsNotNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotNull(FieldSecondaryWeapons))
}

// WritingGuideIsNil applies the IsNil predicate on the "writing_guide" field.
func WritingGuideIsNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIsNull(FieldWritingGuide))
}

// WritingGuideNotNil applies the NotNil predicate on the "writing_guide" field.
func WritingGuideNotNil() predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotNull(FieldWritingGuide))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldLTE(FieldDisplayOrder, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.FieldNEQ(FieldIsActive, v))
}

// HasCoachingPrompt applies the HasEdge predicate on the "coaching_prompt" edge.
func HasCoachingPrompt() predicate.QuestionPattern {
	return predicate.QuestionPattern(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CoachingPromptTable, CoachingPromptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoachingPromptWith applies the HasEdge predicate on the "coaching_prompt" edge with a given conditions (other predicates).
func HasCoachingPromptWith(preds ...predicate.PromptTemplate) predicate.QuestionPattern {
	return predicate.QuestionPattern(func(s *sql.Selector) {
		step := newCoachingPromptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuestionPattern) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuestionPattern) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuestionPattern) predicate.QuestionPattern {
	return predicate.QuestionPattern(sql.NotPredicates(p))
}
