// Code generated by ent, DO NOT EDIT.

package talentprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyName applies equality check predicate on the "company_name" field. It's identical to CompanyNameEQ.
func CompanyName(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldCompanyName, v))
}

// Industry applies equality check predicate on the "industry" field. It's identical to IndustryEQ.
func Industry(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldIndustry, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldSource, v))
}

// Verified applies equality check predicate on the "verified" field. It's identical to VerifiedEQ.
func Verified(v bool) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldVerified, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompanyNameEQ applies the EQ predicate on the "company_name" field.
func CompanyNameEQ(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldCompanyName, v))
}

// CompanyNameNEQ applies the NEQ predicate on the "company_name" field.
func CompanyNameNEQ(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldCompanyName, v))
}

// CompanyNameIn applies the In predicate on the "company_name" field.
func CompanyNameIn(vs ...string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIn(FieldCompanyName, vs...))
}

// CompanyNameNotIn applies the NotIn predicate on the "company_name" field.
func CompanyNameNotIn(vs ...string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotIn(FieldCompanyName, vs...))
}

// CompanyNameGT applies the GT predicate on the "company_name" field.
func CompanyNameGT(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGT(FieldCompanyName, v))
}

// CompanyNameGTE applies the GTE predicate on the "company_name" field.
func CompanyNameGTE(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGTE(FieldCompanyName, v))
}

// CompanyNameLT applies the LT predicate on the "company_name" field.
func CompanyNameLT(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLT(FieldCompanyName, v))
}

// CompanyNameLTE applies the LTE predicate on the "company_name" field.
func CompanyNameLTE(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLTE(FieldCompanyName, v))
}

// CompanyNameContains applies the Contains predicate on the "company_name" field.
func CompanyNameContains(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldContains(FieldCompanyName, v))
}

// CompanyNameHasPrefix applies the HasPrefix predicate on the "company_name" field.
func CompanyNameHasPrefix(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldHasPrefix(FieldCompanyName, v))
}

// CompanyNameHasSuffix applies the HasSuffix predicate on the "company_name" field.
func CompanyNameHasSuffix(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldHasSuffix(FieldCompanyName, v))
}

// CompanyNameEqualFold applies the EqualFold predicate on the "company_name" field.
func CompanyNameEqualFold(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEqualFold(FieldCompanyName, v))
}

// CompanyNameContainsFold applies the ContainsFold predicate on the "company_name" field.
func CompanyNameContainsFold(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldContainsFold(FieldCompanyName, v))
}

// IndustryEQ applies the EQ predicate on the "industry" field.
func IndustryEQ(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldIndustry, v))
}

// IndustryNEQ applies the NEQ predicate on the "industry" field.
func IndustryNEQ(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldIndustry, v))
}

// IndustryIn applies the In predicate on the "industry" field.
func IndustryIn(vs ...string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIn(FieldIndustry, vs...))
}

// IndustryNotIn applies the NotIn predicate on the "industry" field.
func IndustryNotIn(vs ...string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotIn(FieldIndustry, vs...))
}

// IndustryGT applies the GT predicate on the "industry" field.
func IndustryGT(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGT(FieldIndustry, v))
}

// IndustryGTE applies the GTE predicate on the "industry" field.
func IndustryGTE(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGTE(FieldIndustry, v))
}

// IndustryLT applies the LT predicate on the "industry" field.
func IndustryLT(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLT(FieldIndustry, v))
}

// IndustryLTE applies the LTE predicate on the "industry" field.
func IndustryLTE(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLTE(FieldIndustry, v))
}

// IndustryContains applies the Contains predicate on the "industry" field.
func IndustryContains(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldContains(FieldIndustry, v))
}

// IndustryHasPrefix applies the HasPrefix predicate on the "industry" field.
func IndustryHasPrefix(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldHasPrefix(FieldIndustry, v))
}

// IndustryHasSuffix applies the HasSuffix predicate on the "industry" field.
func IndustryHasSuffix(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldHasSuffix(FieldIndustry, v))
}

// IndustryIsNil applies the IsNil predicate on the "industry" field.
func IndustryIsNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIsNull(FieldIndustry))
}

// IndustryNotNil applies the NotNil predicate on the "industry" field.
func IndustryNotNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotNull(FieldIndustry))
}

// IndustryEqualFold applies the EqualFold predicate on the "industry" field.
func IndustryEqualFold(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEqualFold(FieldIndustry, v))
}

// IndustryContainsFold applies the ContainsFold predicate on the "industry" field.
func IndustryContainsFold(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldContainsFold(FieldIndustry, v))
}

// CoreValuesIsNil applies the IsNil predicate on the "core_values" field.
func CoreValuesIsNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIsNull(FieldCoreValues))
}

// CoreValuesNotNil applies the NotNil predicate on the "core_values" field.
func CoreValuesNotNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotNull(FieldCoreValues))
}

// TalentTraitsIsNil applies the IsNil predicate on the "talent_traits" field.
func TalentTraitsIsNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIsNull(FieldTalentTraits))
}

// TalentTraitsNotNil applies the NotNil predicate on the "talent_traits" field.
func TalentTraitsNotNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotNull(FieldTalentTraits))
}

// CultureKeywordsIsNil applies the IsNil predicate on the "culture_keywords" field.
func CultureKeywordsIsNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIsNull(FieldCultureKeywords))
}

// CultureKeywordsNotNil applies the NotNil predicate on the "culture_keywords" field.
func CultureKeywordsNotNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotNull(FieldCultureKeywords))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldContainsFold(FieldSource, v))
}

// VerifiedEQ applies the EQ predicate on the "verified" field.
func VerifiedEQ(v bool) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldEQ(FieldVerified, v))
}

// VerifiedNEQ applies the NEQ predicate on the "verified" field.
func VerifiedNEQ(v bool) predicate.TalentProfile {
	return predicate.TalentProfile(sql.FieldNEQ(FieldVerified, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TalentProfile) predicate.TalentProfile {
	return predicate.TalentProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TalentProfile) predicate.TalentProfile {
	return predicate.TalentProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TalentProfile) predicate.TalentProfile {
	return predicate.TalentProfile(sql.NotPredicates(p))
}
