// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/application"
	"github.com/coby/colight/apps/backend/ent/companyanalysis"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// Application is the model entity for the Application schema.
type Application struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Record last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// References user_profiles(id)
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Company name
	CompanyName string `json:"company_name,omitempty"`
	// Position title
	Position string `json:"position,omitempty"`
	// Job posting URL
	JobURL string `json:"job_url,omitempty"`
	// Application status
	Status application.Status `json:"status,omitempty"`
	// Application deadline
	Deadline *time.Time `json:"deadline,omitempty"`
	// Submission date
	AppliedAt *time.Time `json:"applied_at,omitempty"`
	// Notes
	Notes string `json:"notes,omitempty"`
	// User-defined tags for filtering
	Tags []string `json:"tags,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApplicationQuery when eager-loading is set.
	Edges                         ApplicationEdges `json:"edges"`
	company_analysis_applications *uuid.UUID
	selectValues                  sql.SelectValues
}

// ApplicationEdges holds the relations/edges for other nodes in the graph.
type ApplicationEdges struct {
	// User holds the value of the user edge.
	User *UserProfile `json:"user,omitempty"`
	// Analysis holds the value of the analysis edge.
	Analysis *CompanyAnalysis `json:"analysis,omitempty"`
	// CoverLetters holds the value of the cover_letters edge.
	CoverLetters []*CoverLetter `json:"cover_letters,omitempty"`
	// ExperienceUsages holds the value of the experience_usages edge.
	ExperienceUsages []*ExperienceUsage `json:"experience_usages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApplicationEdges) UserOrErr() (*UserProfile, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: userprofile.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AnalysisOrErr returns the Analysis value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApplicationEdges) AnalysisOrErr() (*CompanyAnalysis, error) {
	if e.Analysis != nil {
		return e.Analysis, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: companyanalysis.Label}
	}
	return nil, &NotLoadedError{edge: "analysis"}
}

// CoverLettersOrErr returns the CoverLetters value or an error if the edge
// was not loaded in eager-loading.
func (e ApplicationEdges) CoverLettersOrErr() ([]*CoverLetter, error) {
	if e.loadedTypes[2] {
		return e.CoverLetters, nil
	}
	return nil, &NotLoadedError{edge: "cover_letters"}
}

// ExperienceUsagesOrErr returns the ExperienceUsages value or an error if the edge
// was not loaded in eager-loading.
func (e ApplicationEdges) ExperienceUsagesOrErr() ([]*ExperienceUsage, error) {
	if e.loadedTypes[3] {
		return e.ExperienceUsages, nil
	}
	return nil, &NotLoadedError{edge: "experience_usages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Application) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case application.FieldTags:
			values[i] = new([]byte)
		case application.FieldCompanyName, application.FieldPosition, application.FieldJobURL, application.FieldStatus, application.FieldNotes:
			values[i] = new(sql.NullString)
		case application.FieldCreatedAt, application.FieldUpdatedAt, application.FieldDeadline, application.FieldAppliedAt:
			values[i] = new(sql.NullTime)
		case application.FieldID, application.FieldUserID:
			values[i] = new(uuid.UUID)
		case application.ForeignKeys[0]: // company_analysis_applications
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Application fields.
func (_m *Application) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case application.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case application.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case application.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case application.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case application.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = value.String
			}
		case application.FieldPosition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = value.String
			}
		case application.FieldJobURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_url", values[i])
			} else if value.Valid {
				_m.JobURL = value.String
			}
		case application.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = application.Status(value.String)
			}
		case application.FieldDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deadline", values[i])
			} else if value.Valid {
				_m.Deadline = new(time.Time)
				*_m.Deadline = value.Time
			}
		case application.FieldAppliedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field applied_at", values[i])
			} else if value.Valid {
				_m.AppliedAt = new(time.Time)
				*_m.AppliedAt = value.Time
			}
		case application.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case application.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case application.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field company_analysis_applications", values[i])
			} else if value.Valid {
				_m.company_analysis_applications = new(uuid.UUID)
				*_m.company_analysis_applications = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Application.
// This includes values selected through modifiers, order, etc.
func (_m *Application) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Application entity.
func (_m *Application) QueryUser() *UserProfileQuery {
	return NewApplicationClient(_m.config).QueryUser(_m)
}

// QueryAnalysis queries the "analysis" edge of the Application entity.
func (_m *Application) QueryAnalysis() *CompanyAnalysisQuery {
	return NewApplicationClient(_m.config).QueryAnalysis(_m)
}

// QueryCoverLetters queries the "cover_letters" edge of the Application entity.
func (_m *Application) QueryCoverLetters() *CoverLetterQuery {
	return NewApplicationClient(_m.config).QueryCoverLetters(_m)
}

// QueryExperienceUsages queries the "experience_usages" edge of the Application entity.
func (_m *Application) QueryExperienceUsages() *ExperienceUsageQuery {
	return NewApplicationClient(_m.config).QueryExperienceUsages(_m)
}

// Update returns a builder for updating this Application.
// Note that you need to call Application.Unwrap() before calling this method if this Application
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Application) Update() *ApplicationUpdateOne {
	return NewApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Application entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Application) Unwrap() *Application {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Application is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Application) String() string {
	var builder strings.Builder
	builder.WriteString("Application(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("company_name=")
	builder.WriteString(_m.CompanyName)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(_m.Position)
	builder.WriteString(", ")
	builder.WriteString("job_url=")
	builder.WriteString(_m.JobURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.Deadline; v != nil {
		builder.WriteString("deadline=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AppliedAt; v != nil {
		builder.WriteString("applied_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteByte(')')
	return builder.String()
}

// Applications is a parsable slice of Application.
type Applications []*Application
