// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/coachingsession"
	"github.com/coby/colight/apps/backend/ent/coverletter"
	"github.com/coby/colight/apps/backend/ent/prompttemplate"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// CoachingSession is the model entity for the CoachingSession schema.
type CoachingSession struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// References auth.users(id)
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Session type
	SessionType coachingsession.SessionType `json:"session_type,omitempty"`
	// Input data
	InputData map[string]interface{} `json:"input_data,omitempty"`
	// AI response data
	OutputData map[string]interface{} `json:"output_data,omitempty"`
	// AI model used
	ModelUsed string `json:"model_used,omitempty"`
	// Input token count
	InputTokens int `json:"input_tokens,omitempty"`
	// Output token count
	OutputTokens int `json:"output_tokens,omitempty"`
	// Cost in KRW
	TotalCostKrw float64 `json:"total_cost_krw,omitempty"`
	// Response latency in ms
	LatencyMs int `json:"latency_ms,omitempty"`
	// User feedback quality score
	QualityScore *float64 `json:"quality_score,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CoachingSessionQuery when eager-loading is set.
	Edges                             CoachingSessionEdges `json:"edges"`
	cover_letter_coaching_sessions    *uuid.UUID
	prompt_template_coaching_sessions *uuid.UUID
	selectValues                      sql.SelectValues
}

// CoachingSessionEdges holds the relations/edges for other nodes in the graph.
type CoachingSessionEdges struct {
	// User holds the value of the user edge.
	User *UserProfile `json:"user,omitempty"`
	// CoverLetter holds the value of the cover_letter edge.
	CoverLetter *CoverLetter `json:"cover_letter,omitempty"`
	// PromptTemplate holds the value of the prompt_template edge.
	PromptTemplate *PromptTemplate `json:"prompt_template,omitempty"`
	// CoverLetterVersions holds the value of the cover_letter_versions edge.
	CoverLetterVersions []*CoverLetterVersion `json:"cover_letter_versions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CoachingSessionEdges) UserOrErr() (*UserProfile, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: userprofile.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CoverLetterOrErr returns the CoverLetter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CoachingSessionEdges) CoverLetterOrErr() (*CoverLetter, error) {
	if e.CoverLetter != nil {
		return e.CoverLetter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: coverletter.Label}
	}
	return nil, &NotLoadedError{edge: "cover_letter"}
}

// PromptTemplateOrErr returns the PromptTemplate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CoachingSessionEdges) PromptTemplateOrErr() (*PromptTemplate, error) {
	if e.PromptTemplate != nil {
		return e.PromptTemplate, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: prompttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "prompt_template"}
}

// CoverLetterVersionsOrErr returns the CoverLetterVersions value or an error if the edge
// was not loaded in eager-loading.
func (e CoachingSessionEdges) CoverLetterVersionsOrErr() ([]*CoverLetterVersion, error) {
	if e.loadedTypes[3] {
		return e.CoverLetterVersions, nil
	}
	return nil, &NotLoadedError{edge: "cover_letter_versions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoachingSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coachingsession.FieldInputData, coachingsession.FieldOutputData:
			values[i] = new([]byte)
		case coachingsession.FieldTotalCostKrw, coachingsession.FieldQualityScore:
			values[i] = new(sql.NullFloat64)
		case coachingsession.FieldInputTokens, coachingsession.FieldOutputTokens, coachingsession.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case coachingsession.FieldSessionType, coachingsession.FieldModelUsed:
			values[i] = new(sql.NullString)
		case coachingsession.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case coachingsession.FieldID, coachingsession.FieldUserID:
			values[i] = new(uuid.UUID)
		case coachingsession.ForeignKeys[0]: // cover_letter_coaching_sessions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case coachingsession.ForeignKeys[1]: // prompt_template_coaching_sessions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoachingSession fields.
func (_m *CoachingSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coachingsession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case coachingsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coachingsession.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case coachingsession.FieldSessionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_type", values[i])
			} else if value.Valid {
				_m.SessionType = coachingsession.SessionType(value.String)
			}
		case coachingsession.FieldInputData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InputData); err != nil {
					return fmt.Errorf("unmarshal field input_data: %w", err)
				}
			}
		case coachingsession.FieldOutputData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field output_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OutputData); err != nil {
					return fmt.Errorf("unmarshal field output_data: %w", err)
				}
			}
		case coachingsession.FieldModelUsed:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_used", values[i])
			} else if value.Valid {
				_m.ModelUsed = value.String
			}
		case coachingsession.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case coachingsession.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case coachingsession.FieldTotalCostKrw:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost_krw", values[i])
			} else if value.Valid {
				_m.TotalCostKrw = value.Float64
			}
		case coachingsession.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = int(value.Int64)
			}
		case coachingsession.FieldQualityScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quality_score", values[i])
			} else if value.Valid {
				_m.QualityScore = new(float64)
				*_m.QualityScore = value.Float64
			}
		case coachingsession.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field cover_letter_coaching_sessions", values[i])
			} else if value.Valid {
				_m.cover_letter_coaching_sessions = new(uuid.UUID)
				*_m.cover_letter_coaching_sessions = *value.S.(*uuid.UUID)
			}
		case coachingsession.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_template_coaching_sessions", values[i])
			} else if value.Valid {
				_m.prompt_template_coaching_sessions = new(uuid.UUID)
				*_m.prompt_template_coaching_sessions = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoachingSession.
// This includes values selected through modifiers, order, etc.
func (_m *CoachingSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CoachingSession entity.
func (_m *CoachingSession) QueryUser() *UserProfileQuery {
	return NewCoachingSessionClient(_m.config).QueryUser(_m)
}

// QueryCoverLetter queries the "cover_letter" edge of the CoachingSession entity.
func (_m *CoachingSession) QueryCoverLetter() *CoverLetterQuery {
	return NewCoachingSessionClient(_m.config).QueryCoverLetter(_m)
}

// QueryPromptTemplate queries the "prompt_template" edge of the CoachingSession entity.
func (_m *CoachingSession) QueryPromptTemplate() *PromptTemplateQuery {
	return NewCoachingSessionClient(_m.config).QueryPromptTemplate(_m)
}

// QueryCoverLetterVersions queries the "cover_letter_versions" edge of the CoachingSession entity.
func (_m *CoachingSession) QueryCoverLetterVersions() *CoverLetterVersionQuery {
	return NewCoachingSessionClient(_m.config).QueryCoverLetterVersions(_m)
}

// Update returns a builder for updating this CoachingSession.
// Note that you need to call CoachingSession.Unwrap() before calling this method if this CoachingSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoachingSession) Update() *CoachingSessionUpdateOne {
	return NewCoachingSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoachingSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoachingSession) Unwrap() *CoachingSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoachingSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoachingSession) String() string {
	var builder strings.Builder
	builder.WriteString("CoachingSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("session_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionType))
	builder.WriteString(", ")
	builder.WriteString("input_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputData))
	builder.WriteString(", ")
	builder.WriteString("output_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputData))
	builder.WriteString(", ")
	builder.WriteString("model_used=")
	builder.WriteString(_m.ModelUsed)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("total_cost_krw=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCostKrw))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	if v := _m.QualityScore; v != nil {
		builder.WriteString("quality_score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CoachingSessions is a parsable slice of CoachingSession.
type CoachingSessions []*CoachingSession
