// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/companyanalysiscache"
	"github.com/google/uuid"
)

// CompanyAnalysisCache is the model entity for the CompanyAnalysisCache schema.
type CompanyAnalysisCache struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// URL hash or company name based key
	CacheKey string `json:"cache_key,omitempty"`
	// Cache type: job_posting, company_info, full_analysis
	CacheType string `json:"cache_type,omitempty"`
	// Cached data
	Data map[string]interface{} `json:"data,omitempty"`
	// Original URL
	SourceURL string `json:"source_url,omitempty"`
	// Company name
	CompanyName string `json:"company_name,omitempty"`
	// Expiration time (365 days for talent profiles, 7 days for news)
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Number of cache hits (popular companies)
	ViewCount    int `json:"view_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompanyAnalysisCache) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case companyanalysiscache.FieldData:
			values[i] = new([]byte)
		case companyanalysiscache.FieldViewCount:
			values[i] = new(sql.NullInt64)
		case companyanalysiscache.FieldCacheKey, companyanalysiscache.FieldCacheType, companyanalysiscache.FieldSourceURL, companyanalysiscache.FieldCompanyName:
			values[i] = new(sql.NullString)
		case companyanalysiscache.FieldCreatedAt, companyanalysiscache.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case companyanalysiscache.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompanyAnalysisCache fields.
func (_m *CompanyAnalysisCache) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case companyanalysiscache.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case companyanalysiscache.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case companyanalysiscache.FieldCacheKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cache_key", values[i])
			} else if value.Valid {
				_m.CacheKey = value.String
			}
		case companyanalysiscache.FieldCacheType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cache_type", values[i])
			} else if value.Valid {
				_m.CacheType = value.String
			}
		case companyanalysiscache.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		case companyanalysiscache.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case companyanalysiscache.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = value.String
			}
		case companyanalysiscache.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case companyanalysiscache.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompanyAnalysisCache.
// This includes values selected through modifiers, order, etc.
func (_m *CompanyAnalysisCache) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CompanyAnalysisCache.
// Note that you need to call CompanyAnalysisCache.Unwrap() before calling this method if this CompanyAnalysisCache
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompanyAnalysisCache) Update() *CompanyAnalysisCacheUpdateOne {
	return NewCompanyAnalysisCacheClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompanyAnalysisCache entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompanyAnalysisCache) Unwrap() *CompanyAnalysisCache {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompanyAnalysisCache is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompanyAnalysisCache) String() string {
	var builder strings.Builder
	builder.WriteString("CompanyAnalysisCache(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cache_key=")
	builder.WriteString(_m.CacheKey)
	builder.WriteString(", ")
	builder.WriteString("cache_type=")
	builder.WriteString(_m.CacheType)
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("company_name=")
	builder.WriteString(_m.CompanyName)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteByte(')')
	return builder.String()
}

// CompanyAnalysisCaches is a parsable slice of CompanyAnalysisCache.
type CompanyAnalysisCaches []*CompanyAnalysisCache
