// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/coverletterversion"
	"github.com/coby/colight/apps/backend/ent/predicate"
)

// CoverLetterVersionDelete is the builder for deleting a CoverLetterVersion entity.
type CoverLetterVersionDelete struct {
	config
	hooks    []Hook
	mutation *CoverLetterVersionMutation
}

// Where appends a list predicates to the CoverLetterVersionDelete builder.
func (_d *CoverLetterVersionDelete) Where(ps ...predicate.CoverLetterVersion) *CoverLetterVersionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CoverLetterVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CoverLetterVersionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CoverLetterVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(coverletterversion.Table, sqlgraph.NewFieldSpec(coverletterversion.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CoverLetterVersionDeleteOne is the builder for deleting a single CoverLetterVersion entity.
type CoverLetterVersionDeleteOne struct {
	_d *CoverLetterVersionDelete
}

// Where appends a list predicates to the CoverLetterVersionDelete builder.
func (_d *CoverLetterVersionDeleteOne) Where(ps ...predicate.CoverLetterVersion) *CoverLetterVersionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CoverLetterVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coverletterversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CoverLetterVersionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
