// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/deletionrequest"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// DeletionRequest is the model entity for the DeletionRequest schema.
type DeletionRequest struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// References user_profiles(id)
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Reason for deletion request
	Reason string `json:"reason,omitempty"`
	// When the deletion will be executed (30 days from request)
	ScheduledAt time.Time `json:"scheduled_at,omitempty"`
	// Deletion request status
	Status deletionrequest.Status `json:"status,omitempty"`
	// Admin who initiated the request
	RequestedBy uuid.UUID `json:"requested_by,omitempty"`
	// When the request was cancelled
	CancelledAt *time.Time `json:"cancelled_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeletionRequestQuery when eager-loading is set.
	Edges        DeletionRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeletionRequestEdges holds the relations/edges for other nodes in the graph.
type DeletionRequestEdges struct {
	// User holds the value of the user edge.
	User *UserProfile `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeletionRequestEdges) UserOrErr() (*UserProfile, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: userprofile.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeletionRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deletionrequest.FieldReason, deletionrequest.FieldStatus:
			values[i] = new(sql.NullString)
		case deletionrequest.FieldCreatedAt, deletionrequest.FieldScheduledAt, deletionrequest.FieldCancelledAt:
			values[i] = new(sql.NullTime)
		case deletionrequest.FieldID, deletionrequest.FieldUserID, deletionrequest.FieldRequestedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeletionRequest fields.
func (_m *DeletionRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deletionrequest.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case deletionrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deletionrequest.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case deletionrequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case deletionrequest.FieldScheduledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_at", values[i])
			} else if value.Valid {
				_m.ScheduledAt = value.Time
			}
		case deletionrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = deletionrequest.Status(value.String)
			}
		case deletionrequest.FieldRequestedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field requested_by", values[i])
			} else if value != nil {
				_m.RequestedBy = *value
			}
		case deletionrequest.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(time.Time)
				*_m.CancelledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeletionRequest.
// This includes values selected through modifiers, order, etc.
func (_m *DeletionRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the DeletionRequest entity.
func (_m *DeletionRequest) QueryUser() *UserProfileQuery {
	return NewDeletionRequestClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this DeletionRequest.
// Note that you need to call DeletionRequest.Unwrap() before calling this method if this DeletionRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeletionRequest) Update() *DeletionRequestUpdateOne {
	return NewDeletionRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeletionRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeletionRequest) Unwrap() *DeletionRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeletionRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeletionRequest) String() string {
	var builder strings.Builder
	builder.WriteString("DeletionRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("scheduled_at=")
	builder.WriteString(_m.ScheduledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("requested_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedBy))
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DeletionRequests is a parsable slice of DeletionRequest.
type DeletionRequests []*DeletionRequest
