// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experiencetag"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/google/uuid"
)

// ExperienceTagUpdate is the builder for updating ExperienceTag entities.
type ExperienceTagUpdate struct {
	config
	hooks    []Hook
	mutation *ExperienceTagMutation
}

// Where appends a list predicates to the ExperienceTagUpdate builder.
func (_u *ExperienceTagUpdate) Where(ps ...predicate.ExperienceTag) *ExperienceTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTagName sets the "tag_name" field.
func (_u *ExperienceTagUpdate) SetTagName(v string) *ExperienceTagUpdate {
	_u.mutation.SetTagName(v)
	return _u
}

// SetNillableTagName sets the "tag_name" field if the given value is not nil.
func (_u *ExperienceTagUpdate) SetNillableTagName(v *string) *ExperienceTagUpdate {
	if v != nil {
		_u.SetTagName(*v)
	}
	return _u
}

// SetTagType sets the "tag_type" field.
func (_u *ExperienceTagUpdate) SetTagType(v string) *ExperienceTagUpdate {
	_u.mutation.SetTagType(v)
	return _u
}

// SetNillableTagType sets the "tag_type" field if the given value is not nil.
func (_u *ExperienceTagUpdate) SetNillableTagType(v *string) *ExperienceTagUpdate {
	if v != nil {
		_u.SetTagType(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *ExperienceTagUpdate) SetConfidence(v float64) *ExperienceTagUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *ExperienceTagUpdate) SetNillableConfidence(v *float64) *ExperienceTagUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *ExperienceTagUpdate) AddConfidence(v float64) *ExperienceTagUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetExperienceID sets the "experience" edge to the Experience entity by ID.
func (_u *ExperienceTagUpdate) SetExperienceID(id uuid.UUID) *ExperienceTagUpdate {
	_u.mutation.SetExperienceID(id)
	return _u
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_u *ExperienceTagUpdate) SetExperience(v *Experience) *ExperienceTagUpdate {
	return _u.SetExperienceID(v.ID)
}

// Mutation returns the ExperienceTagMutation object of the builder.
func (_u *ExperienceTagUpdate) Mutation() *ExperienceTagMutation {
	return _u.mutation
}

// ClearExperience clears the "experience" edge to the Experience entity.
func (_u *ExperienceTagUpdate) ClearExperience() *ExperienceTagUpdate {
	_u.mutation.ClearExperience()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExperienceTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExperienceTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceTagUpdate) check() error {
	if v, ok := _u.mutation.TagName(); ok {
		if err := experiencetag.TagNameValidator(v); err != nil {
			return &ValidationError{Name: "tag_name", err: fmt.Errorf(`ent: validator failed for field "ExperienceTag.tag_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TagType(); ok {
		if err := experiencetag.TagTypeValidator(v); err != nil {
			return &ValidationError{Name: "tag_type", err: fmt.Errorf(`ent: validator failed for field "ExperienceTag.tag_type": %w`, err)}
		}
	}
	if _u.mutation.ExperienceCleared() && len(_u.mutation.ExperienceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExperienceTag.experience"`)
	}
	return nil
}

func (_u *ExperienceTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experiencetag.Table, experiencetag.Columns, sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TagName(); ok {
		_spec.SetField(experiencetag.FieldTagName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TagType(); ok {
		_spec.SetField(experiencetag.FieldTagType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(experiencetag.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(experiencetag.FieldConfidence, field.TypeFloat64, value)
	}
	if _u.mutation.ExperienceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experiencetag.ExperienceTable,
			Columns: []string{experiencetag.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experiencetag.ExperienceTable,
			Columns: []string{experiencetag.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experiencetag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExperienceTagUpdateOne is the builder for updating a single ExperienceTag entity.
type ExperienceTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExperienceTagMutation
}

// SetTagName sets the "tag_name" field.
func (_u *ExperienceTagUpdateOne) SetTagName(v string) *ExperienceTagUpdateOne {
	_u.mutation.SetTagName(v)
	return _u
}

// SetNillableTagName sets the "tag_name" field if the given value is not nil.
func (_u *ExperienceTagUpdateOne) SetNillableTagName(v *string) *ExperienceTagUpdateOne {
	if v != nil {
		_u.SetTagName(*v)
	}
	return _u
}

// SetTagType sets the "tag_type" field.
func (_u *ExperienceTagUpdateOne) SetTagType(v string) *ExperienceTagUpdateOne {
	_u.mutation.SetTagType(v)
	return _u
}

// SetNillableTagType sets the "tag_type" field if the given value is not nil.
func (_u *ExperienceTagUpdateOne) SetNillableTagType(v *string) *ExperienceTagUpdateOne {
	if v != nil {
		_u.SetTagType(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *ExperienceTagUpdateOne) SetConfidence(v float64) *ExperienceTagUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *ExperienceTagUpdateOne) SetNillableConfidence(v *float64) *ExperienceTagUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *ExperienceTagUpdateOne) AddConfidence(v float64) *ExperienceTagUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetExperienceID sets the "experience" edge to the Experience entity by ID.
func (_u *ExperienceTagUpdateOne) SetExperienceID(id uuid.UUID) *ExperienceTagUpdateOne {
	_u.mutation.SetExperienceID(id)
	return _u
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_u *ExperienceTagUpdateOne) SetExperience(v *Experience) *ExperienceTagUpdateOne {
	return _u.SetExperienceID(v.ID)
}

// Mutation returns the ExperienceTagMutation object of the builder.
func (_u *ExperienceTagUpdateOne) Mutation() *ExperienceTagMutation {
	return _u.mutation
}

// ClearExperience clears the "experience" edge to the Experience entity.
func (_u *ExperienceTagUpdateOne) ClearExperience() *ExperienceTagUpdateOne {
	_u.mutation.ClearExperience()
	return _u
}

// Where appends a list predicates to the ExperienceTagUpdate builder.
func (_u *ExperienceTagUpdateOne) Where(ps ...predicate.ExperienceTag) *ExperienceTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExperienceTagUpdateOne) Select(field string, fields ...string) *ExperienceTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExperienceTag entity.
func (_u *ExperienceTagUpdateOne) Save(ctx context.Context) (*ExperienceTag, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceTagUpdateOne) SaveX(ctx context.Context) *ExperienceTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExperienceTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceTagUpdateOne) check() error {
	if v, ok := _u.mutation.TagName(); ok {
		if err := experiencetag.TagNameValidator(v); err != nil {
			return &ValidationError{Name: "tag_name", err: fmt.Errorf(`ent: validator failed for field "ExperienceTag.tag_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TagType(); ok {
		if err := experiencetag.TagTypeValidator(v); err != nil {
			return &ValidationError{Name: "tag_type", err: fmt.Errorf(`ent: validator failed for field "ExperienceTag.tag_type": %w`, err)}
		}
	}
	if _u.mutation.ExperienceCleared() && len(_u.mutation.ExperienceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExperienceTag.experience"`)
	}
	return nil
}

func (_u *ExperienceTagUpdateOne) sqlSave(ctx context.Context) (_node *ExperienceTag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experiencetag.Table, experiencetag.Columns, sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExperienceTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, experiencetag.FieldID)
		for _, f := range fields {
			if !experiencetag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != experiencetag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TagName(); ok {
		_spec.SetField(experiencetag.FieldTagName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TagType(); ok {
		_spec.SetField(experiencetag.FieldTagType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(experiencetag.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(experiencetag.FieldConfidence, field.TypeFloat64, value)
	}
	if _u.mutation.ExperienceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experiencetag.ExperienceTable,
			Columns: []string{experiencetag.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experiencetag.ExperienceTable,
			Columns: []string{experiencetag.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ExperienceTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experiencetag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
