// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experienceweapon"
	"github.com/google/uuid"
)

// ExperienceWeaponCreate is the builder for creating a ExperienceWeapon entity.
type ExperienceWeaponCreate struct {
	config
	mutation *ExperienceWeaponMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExperienceWeaponCreate) SetCreatedAt(v time.Time) *ExperienceWeaponCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableCreatedAt(v *time.Time) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetWeaponCode sets the "weapon_code" field.
func (_c *ExperienceWeaponCreate) SetWeaponCode(v string) *ExperienceWeaponCreate {
	_c.mutation.SetWeaponCode(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *ExperienceWeaponCreate) SetConfidence(v float64) *ExperienceWeaponCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableConfidence(v *float64) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetIsPrimary sets the "is_primary" field.
func (_c *ExperienceWeaponCreate) SetIsPrimary(v bool) *ExperienceWeaponCreate {
	_c.mutation.SetIsPrimary(v)
	return _c
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableIsPrimary(v *bool) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetIsPrimary(*v)
	}
	return _c
}

// SetReasoning sets the "reasoning" field.
func (_c *ExperienceWeaponCreate) SetReasoning(v string) *ExperienceWeaponCreate {
	_c.mutation.SetReasoning(v)
	return _c
}

// SetNillableReasoning sets the "reasoning" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableReasoning(v *string) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetReasoning(*v)
	}
	return _c
}

// SetUserConfirmed sets the "user_confirmed" field.
func (_c *ExperienceWeaponCreate) SetUserConfirmed(v bool) *ExperienceWeaponCreate {
	_c.mutation.SetUserConfirmed(v)
	return _c
}

// SetNillableUserConfirmed sets the "user_confirmed" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableUserConfirmed(v *bool) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetUserConfirmed(*v)
	}
	return _c
}

// SetUserModified sets the "user_modified" field.
func (_c *ExperienceWeaponCreate) SetUserModified(v bool) *ExperienceWeaponCreate {
	_c.mutation.SetUserModified(v)
	return _c
}

// SetNillableUserModified sets the "user_modified" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableUserModified(v *bool) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetUserModified(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExperienceWeaponCreate) SetID(v uuid.UUID) *ExperienceWeaponCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExperienceWeaponCreate) SetNillableID(v *uuid.UUID) *ExperienceWeaponCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetExperienceID sets the "experience" edge to the Experience entity by ID.
func (_c *ExperienceWeaponCreate) SetExperienceID(id uuid.UUID) *ExperienceWeaponCreate {
	_c.mutation.SetExperienceID(id)
	return _c
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_c *ExperienceWeaponCreate) SetExperience(v *Experience) *ExperienceWeaponCreate {
	return _c.SetExperienceID(v.ID)
}

// Mutation returns the ExperienceWeaponMutation object of the builder.
func (_c *ExperienceWeaponCreate) Mutation() *ExperienceWeaponMutation {
	return _c.mutation
}

// Save creates the ExperienceWeapon in the database.
func (_c *ExperienceWeaponCreate) Save(ctx context.Context) (*ExperienceWeapon, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExperienceWeaponCreate) SaveX(ctx context.Context) *ExperienceWeapon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceWeaponCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceWeaponCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExperienceWeaponCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := experienceweapon.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := experienceweapon.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		v := experienceweapon.DefaultIsPrimary
		_c.mutation.SetIsPrimary(v)
	}
	if _, ok := _c.mutation.UserConfirmed(); !ok {
		v := experienceweapon.DefaultUserConfirmed
		_c.mutation.SetUserConfirmed(v)
	}
	if _, ok := _c.mutation.UserModified(); !ok {
		v := experienceweapon.DefaultUserModified
		_c.mutation.SetUserModified(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := experienceweapon.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExperienceWeaponCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExperienceWeapon.created_at"`)}
	}
	if _, ok := _c.mutation.WeaponCode(); !ok {
		return &ValidationError{Name: "weapon_code", err: errors.New(`ent: missing required field "ExperienceWeapon.weapon_code"`)}
	}
	if v, ok := _c.mutation.WeaponCode(); ok {
		if err := experienceweapon.WeaponCodeValidator(v); err != nil {
			return &ValidationError{Name: "weapon_code", err: fmt.Errorf(`ent: validator failed for field "ExperienceWeapon.weapon_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "ExperienceWeapon.confidence"`)}
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		return &ValidationError{Name: "is_primary", err: errors.New(`ent: missing required field "ExperienceWeapon.is_primary"`)}
	}
	if _, ok := _c.mutation.UserConfirmed(); !ok {
		return &ValidationError{Name: "user_confirmed", err: errors.New(`ent: missing required field "ExperienceWeapon.user_confirmed"`)}
	}
	if _, ok := _c.mutation.UserModified(); !ok {
		return &ValidationError{Name: "user_modified", err: errors.New(`ent: missing required field "ExperienceWeapon.user_modified"`)}
	}
	if len(_c.mutation.ExperienceIDs()) == 0 {
		return &ValidationError{Name: "experience", err: errors.New(`ent: missing required edge "ExperienceWeapon.experience"`)}
	}
	return nil
}

func (_c *ExperienceWeaponCreate) sqlSave(ctx context.Context) (*ExperienceWeapon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExperienceWeaponCreate) createSpec() (*ExperienceWeapon, *sqlgraph.CreateSpec) {
	var (
		_node = &ExperienceWeapon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(experienceweapon.Table, sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(experienceweapon.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.WeaponCode(); ok {
		_spec.SetField(experienceweapon.FieldWeaponCode, field.TypeString, value)
		_node.WeaponCode = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(experienceweapon.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.IsPrimary(); ok {
		_spec.SetField(experienceweapon.FieldIsPrimary, field.TypeBool, value)
		_node.IsPrimary = value
	}
	if value, ok := _c.mutation.Reasoning(); ok {
		_spec.SetField(experienceweapon.FieldReasoning, field.TypeString, value)
		_node.Reasoning = value
	}
	if value, ok := _c.mutation.UserConfirmed(); ok {
		_spec.SetField(experienceweapon.FieldUserConfirmed, field.TypeBool, value)
		_node.UserConfirmed = value
	}
	if value, ok := _c.mutation.UserModified(); ok {
		_spec.SetField(experienceweapon.FieldUserModified, field.TypeBool, value)
		_node.UserModified = value
	}
	if nodes := _c.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experienceweapon.ExperienceTable,
			Columns: []string{experienceweapon.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.experience_weapons = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExperienceWeaponCreateBulk is the builder for creating many ExperienceWeapon entities in bulk.
type ExperienceWeaponCreateBulk struct {
	config
	err      error
	builders []*ExperienceWeaponCreate
}

// Save creates the ExperienceWeapon entities in the database.
func (_c *ExperienceWeaponCreateBulk) Save(ctx context.Context) ([]*ExperienceWeapon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExperienceWeapon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExperienceWeaponMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExperienceWeaponCreateBulk) SaveX(ctx context.Context) []*ExperienceWeapon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceWeaponCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceWeaponCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
