// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experiencetag"
	"github.com/coby/colight/apps/backend/ent/experienceusage"
	"github.com/coby/colight/apps/backend/ent/experienceweapon"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// ExperienceCreate is the builder for creating a Experience entity.
type ExperienceCreate struct {
	config
	mutation *ExperienceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExperienceCreate) SetCreatedAt(v time.Time) *ExperienceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableCreatedAt(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExperienceCreate) SetUpdatedAt(v time.Time) *ExperienceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableUpdatedAt(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ExperienceCreate) SetUserID(v uuid.UUID) *ExperienceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ExperienceCreate) SetTitle(v string) *ExperienceCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *ExperienceCreate) SetCategory(v string) *ExperienceCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableCategory(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *ExperienceCreate) SetPeriodStart(v time.Time) *ExperienceCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillablePeriodStart(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetPeriodStart(*v)
	}
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *ExperienceCreate) SetPeriodEnd(v time.Time) *ExperienceCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillablePeriodEnd(v *time.Time) *ExperienceCreate {
	if v != nil {
		_c.SetPeriodEnd(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *ExperienceCreate) SetRole(v string) *ExperienceCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableRole(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ExperienceCreate) SetContent(v string) *ExperienceCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *ExperienceCreate) SetResult(v string) *ExperienceCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableResult(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetStarSituation sets the "star_situation" field.
func (_c *ExperienceCreate) SetStarSituation(v string) *ExperienceCreate {
	_c.mutation.SetStarSituation(v)
	return _c
}

// SetNillableStarSituation sets the "star_situation" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableStarSituation(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetStarSituation(*v)
	}
	return _c
}

// SetStarTask sets the "star_task" field.
func (_c *ExperienceCreate) SetStarTask(v string) *ExperienceCreate {
	_c.mutation.SetStarTask(v)
	return _c
}

// SetNillableStarTask sets the "star_task" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableStarTask(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetStarTask(*v)
	}
	return _c
}

// SetStarAction sets the "star_action" field.
func (_c *ExperienceCreate) SetStarAction(v string) *ExperienceCreate {
	_c.mutation.SetStarAction(v)
	return _c
}

// SetNillableStarAction sets the "star_action" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableStarAction(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetStarAction(*v)
	}
	return _c
}

// SetStarResult sets the "star_result" field.
func (_c *ExperienceCreate) SetStarResult(v string) *ExperienceCreate {
	_c.mutation.SetStarResult(v)
	return _c
}

// SetNillableStarResult sets the "star_result" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableStarResult(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetStarResult(*v)
	}
	return _c
}

// SetKeywords sets the "keywords" field.
func (_c *ExperienceCreate) SetKeywords(v []string) *ExperienceCreate {
	_c.mutation.SetKeywords(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *ExperienceCreate) SetSource(v string) *ExperienceCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableSource(v *string) *ExperienceCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetIsArchived sets the "is_archived" field.
func (_c *ExperienceCreate) SetIsArchived(v bool) *ExperienceCreate {
	_c.mutation.SetIsArchived(v)
	return _c
}

// SetNillableIsArchived sets the "is_archived" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableIsArchived(v *bool) *ExperienceCreate {
	if v != nil {
		_c.SetIsArchived(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExperienceCreate) SetID(v uuid.UUID) *ExperienceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExperienceCreate) SetNillableID(v *uuid.UUID) *ExperienceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_c *ExperienceCreate) SetUser(v *UserProfile) *ExperienceCreate {
	return _c.SetUserID(v.ID)
}

// AddTagIDs adds the "tags" edge to the ExperienceTag entity by IDs.
func (_c *ExperienceCreate) AddTagIDs(ids ...uuid.UUID) *ExperienceCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the ExperienceTag entity.
func (_c *ExperienceCreate) AddTags(v ...*ExperienceTag) *ExperienceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// AddWeaponIDs adds the "weapons" edge to the ExperienceWeapon entity by IDs.
func (_c *ExperienceCreate) AddWeaponIDs(ids ...uuid.UUID) *ExperienceCreate {
	_c.mutation.AddWeaponIDs(ids...)
	return _c
}

// AddWeapons adds the "weapons" edges to the ExperienceWeapon entity.
func (_c *ExperienceCreate) AddWeapons(v ...*ExperienceWeapon) *ExperienceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWeaponIDs(ids...)
}

// AddUsageIDs adds the "usages" edge to the ExperienceUsage entity by IDs.
func (_c *ExperienceCreate) AddUsageIDs(ids ...uuid.UUID) *ExperienceCreate {
	_c.mutation.AddUsageIDs(ids...)
	return _c
}

// AddUsages adds the "usages" edges to the ExperienceUsage entity.
func (_c *ExperienceCreate) AddUsages(v ...*ExperienceUsage) *ExperienceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageIDs(ids...)
}

// Mutation returns the ExperienceMutation object of the builder.
func (_c *ExperienceCreate) Mutation() *ExperienceMutation {
	return _c.mutation
}

// Save creates the Experience in the database.
func (_c *ExperienceCreate) Save(ctx context.Context) (*Experience, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExperienceCreate) SaveX(ctx context.Context) *Experience {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExperienceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := experience.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := experience.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := experience.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.IsArchived(); !ok {
		v := experience.DefaultIsArchived
		_c.mutation.SetIsArchived(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := experience.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExperienceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Experience.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Experience.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Experience.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Experience.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := experience.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Experience.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := experience.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Experience.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := experience.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Experience.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Experience.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := experience.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Experience.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Experience.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := experience.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Experience.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsArchived(); !ok {
		return &ValidationError{Name: "is_archived", err: errors.New(`ent: missing required field "Experience.is_archived"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Experience.user"`)}
	}
	return nil
}

func (_c *ExperienceCreate) sqlSave(ctx context.Context) (*Experience, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExperienceCreate) createSpec() (*Experience, *sqlgraph.CreateSpec) {
	var (
		_node = &Experience{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(experience.Table, sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(experience.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(experience.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(experience.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(experience.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(experience.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = &value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(experience.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = &value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(experience.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(experience.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(experience.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.StarSituation(); ok {
		_spec.SetField(experience.FieldStarSituation, field.TypeString, value)
		_node.StarSituation = value
	}
	if value, ok := _c.mutation.StarTask(); ok {
		_spec.SetField(experience.FieldStarTask, field.TypeString, value)
		_node.StarTask = value
	}
	if value, ok := _c.mutation.StarAction(); ok {
		_spec.SetField(experience.FieldStarAction, field.TypeString, value)
		_node.StarAction = value
	}
	if value, ok := _c.mutation.StarResult(); ok {
		_spec.SetField(experience.FieldStarResult, field.TypeString, value)
		_node.StarResult = value
	}
	if value, ok := _c.mutation.Keywords(); ok {
		_spec.SetField(experience.FieldKeywords, field.TypeJSON, value)
		_node.Keywords = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(experience.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.IsArchived(); ok {
		_spec.SetField(experience.FieldIsArchived, field.TypeBool, value)
		_node.IsArchived = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WeaponsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExperienceCreateBulk is the builder for creating many Experience entities in bulk.
type ExperienceCreateBulk struct {
	config
	err      error
	builders []*ExperienceCreate
}

// Save creates the Experience entities in the database.
func (_c *ExperienceCreateBulk) Save(ctx context.Context) ([]*Experience, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Experience, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExperienceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExperienceCreateBulk) SaveX(ctx context.Context) []*Experience {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
