// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experienceweapon"
	"github.com/google/uuid"
)

// ExperienceWeapon is the model entity for the ExperienceWeapon schema.
type ExperienceWeapon struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Weapon category code (W01, W01-A, etc.)
	WeaponCode string `json:"weapon_code,omitempty"`
	// AI classification confidence (0~1)
	Confidence float64 `json:"confidence,omitempty"`
	// Whether this is the primary weapon
	IsPrimary bool `json:"is_primary,omitempty"`
	// AI classification reasoning
	Reasoning string `json:"reasoning,omitempty"`
	// Whether user confirmed the classification
	UserConfirmed bool `json:"user_confirmed,omitempty"`
	// Whether user modified the classification
	UserModified bool `json:"user_modified,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExperienceWeaponQuery when eager-loading is set.
	Edges                              ExperienceWeaponEdges `json:"edges"`
	experience_weapons                 *uuid.UUID
	weapon_category_experience_weapons *uuid.UUID
	selectValues                       sql.SelectValues
}

// ExperienceWeaponEdges holds the relations/edges for other nodes in the graph.
type ExperienceWeaponEdges struct {
	// Experience holds the value of the experience edge.
	Experience *Experience `json:"experience,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ExperienceOrErr returns the Experience value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExperienceWeaponEdges) ExperienceOrErr() (*Experience, error) {
	if e.Experience != nil {
		return e.Experience, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: experience.Label}
	}
	return nil, &NotLoadedError{edge: "experience"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExperienceWeapon) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case experienceweapon.FieldIsPrimary, experienceweapon.FieldUserConfirmed, experienceweapon.FieldUserModified:
			values[i] = new(sql.NullBool)
		case experienceweapon.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case experienceweapon.FieldWeaponCode, experienceweapon.FieldReasoning:
			values[i] = new(sql.NullString)
		case experienceweapon.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case experienceweapon.FieldID:
			values[i] = new(uuid.UUID)
		case experienceweapon.ForeignKeys[0]: // experience_weapons
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case experienceweapon.ForeignKeys[1]: // weapon_category_experience_weapons
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExperienceWeapon fields.
func (_m *ExperienceWeapon) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case experienceweapon.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case experienceweapon.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case experienceweapon.FieldWeaponCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field weapon_code", values[i])
			} else if value.Valid {
				_m.WeaponCode = value.String
			}
		case experienceweapon.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case experienceweapon.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				_m.IsPrimary = value.Bool
			}
		case experienceweapon.FieldReasoning:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning", values[i])
			} else if value.Valid {
				_m.Reasoning = value.String
			}
		case experienceweapon.FieldUserConfirmed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field user_confirmed", values[i])
			} else if value.Valid {
				_m.UserConfirmed = value.Bool
			}
		case experienceweapon.FieldUserModified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field user_modified", values[i])
			} else if value.Valid {
				_m.UserModified = value.Bool
			}
		case experienceweapon.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field experience_weapons", values[i])
			} else if value.Valid {
				_m.experience_weapons = new(uuid.UUID)
				*_m.experience_weapons = *value.S.(*uuid.UUID)
			}
		case experienceweapon.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field weapon_category_experience_weapons", values[i])
			} else if value.Valid {
				_m.weapon_category_experience_weapons = new(uuid.UUID)
				*_m.weapon_category_experience_weapons = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExperienceWeapon.
// This includes values selected through modifiers, order, etc.
func (_m *ExperienceWeapon) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExperience queries the "experience" edge of the ExperienceWeapon entity.
func (_m *ExperienceWeapon) QueryExperience() *ExperienceQuery {
	return NewExperienceWeaponClient(_m.config).QueryExperience(_m)
}

// Update returns a builder for updating this ExperienceWeapon.
// Note that you need to call ExperienceWeapon.Unwrap() before calling this method if this ExperienceWeapon
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExperienceWeapon) Update() *ExperienceWeaponUpdateOne {
	return NewExperienceWeaponClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExperienceWeapon entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExperienceWeapon) Unwrap() *ExperienceWeapon {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExperienceWeapon is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExperienceWeapon) String() string {
	var builder strings.Builder
	builder.WriteString("ExperienceWeapon(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("weapon_code=")
	builder.WriteString(_m.WeaponCode)
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("is_primary=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPrimary))
	builder.WriteString(", ")
	builder.WriteString("reasoning=")
	builder.WriteString(_m.Reasoning)
	builder.WriteString(", ")
	builder.WriteString("user_confirmed=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserConfirmed))
	builder.WriteString(", ")
	builder.WriteString("user_modified=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserModified))
	builder.WriteByte(')')
	return builder.String()
}

// ExperienceWeapons is a parsable slice of ExperienceWeapon.
type ExperienceWeapons []*ExperienceWeapon
