// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/application"
	"github.com/coby/colight/apps/backend/ent/coverletter"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experienceusage"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// ExperienceUsageCreate is the builder for creating a ExperienceUsage entity.
type ExperienceUsageCreate struct {
	config
	mutation *ExperienceUsageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExperienceUsageCreate) SetCreatedAt(v time.Time) *ExperienceUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableCreatedAt(v *time.Time) *ExperienceUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ExperienceUsageCreate) SetUserID(v uuid.UUID) *ExperienceUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetQuestionText sets the "question_text" field.
func (_c *ExperienceUsageCreate) SetQuestionText(v string) *ExperienceUsageCreate {
	_c.mutation.SetQuestionText(v)
	return _c
}

// SetNillableQuestionText sets the "question_text" field if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableQuestionText(v *string) *ExperienceUsageCreate {
	if v != nil {
		_c.SetQuestionText(*v)
	}
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *ExperienceUsageCreate) SetCompanyName(v string) *ExperienceUsageCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableCompanyName(v *string) *ExperienceUsageCreate {
	if v != nil {
		_c.SetCompanyName(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *ExperienceUsageCreate) SetUsedAt(v time.Time) *ExperienceUsageCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableUsedAt(v *time.Time) *ExperienceUsageCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExperienceUsageCreate) SetID(v uuid.UUID) *ExperienceUsageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableID(v *uuid.UUID) *ExperienceUsageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetExperienceID sets the "experience" edge to the Experience entity by ID.
func (_c *ExperienceUsageCreate) SetExperienceID(id uuid.UUID) *ExperienceUsageCreate {
	_c.mutation.SetExperienceID(id)
	return _c
}

// SetExperience sets the "experience" edge to the Experience entity.
func (_c *ExperienceUsageCreate) SetExperience(v *Experience) *ExperienceUsageCreate {
	return _c.SetExperienceID(v.ID)
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_c *ExperienceUsageCreate) SetUser(v *UserProfile) *ExperienceUsageCreate {
	return _c.SetUserID(v.ID)
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (_c *ExperienceUsageCreate) SetApplicationID(id uuid.UUID) *ExperienceUsageCreate {
	_c.mutation.SetApplicationID(id)
	return _c
}

// SetNillableApplicationID sets the "application" edge to the Application entity by ID if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableApplicationID(id *uuid.UUID) *ExperienceUsageCreate {
	if id != nil {
		_c = _c.SetApplicationID(*id)
	}
	return _c
}

// SetApplication sets the "application" edge to the Application entity.
func (_c *ExperienceUsageCreate) SetApplication(v *Application) *ExperienceUsageCreate {
	return _c.SetApplicationID(v.ID)
}

// SetCoverLetterID sets the "cover_letter" edge to the CoverLetter entity by ID.
func (_c *ExperienceUsageCreate) SetCoverLetterID(id uuid.UUID) *ExperienceUsageCreate {
	_c.mutation.SetCoverLetterID(id)
	return _c
}

// SetNillableCoverLetterID sets the "cover_letter" edge to the CoverLetter entity by ID if the given value is not nil.
func (_c *ExperienceUsageCreate) SetNillableCoverLetterID(id *uuid.UUID) *ExperienceUsageCreate {
	if id != nil {
		_c = _c.SetCoverLetterID(*id)
	}
	return _c
}

// SetCoverLetter sets the "cover_letter" edge to the CoverLetter entity.
func (_c *ExperienceUsageCreate) SetCoverLetter(v *CoverLetter) *ExperienceUsageCreate {
	return _c.SetCoverLetterID(v.ID)
}

// Mutation returns the ExperienceUsageMutation object of the builder.
func (_c *ExperienceUsageCreate) Mutation() *ExperienceUsageMutation {
	return _c.mutation
}

// Save creates the ExperienceUsage in the database.
func (_c *ExperienceUsageCreate) Save(ctx context.Context) (*ExperienceUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExperienceUsageCreate) SaveX(ctx context.Context) *ExperienceUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExperienceUsageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := experienceusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		v := experienceusage.DefaultUsedAt()
		_c.mutation.SetUsedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := experienceusage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExperienceUsageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExperienceUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ExperienceUsage.user_id"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := experienceusage.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "ExperienceUsage.company_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsedAt(); !ok {
		return &ValidationError{Name: "used_at", err: errors.New(`ent: missing required field "ExperienceUsage.used_at"`)}
	}
	if len(_c.mutation.ExperienceIDs()) == 0 {
		return &ValidationError{Name: "experience", err: errors.New(`ent: missing required edge "ExperienceUsage.experience"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ExperienceUsage.user"`)}
	}
	return nil
}

func (_c *ExperienceUsageCreate) sqlSave(ctx context.Context) (*ExperienceUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExperienceUsageCreate) createSpec() (*ExperienceUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &ExperienceUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(experienceusage.Table, sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(experienceusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.QuestionText(); ok {
		_spec.SetField(experienceusage.FieldQuestionText, field.TypeString, value)
		_node.QuestionText = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(experienceusage.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(experienceusage.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = value
	}
	if nodes := _c.mutation.ExperienceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experienceusage.ExperienceTable,
			Columns: []string{experienceusage.ExperienceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.experience_usages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experienceusage.UserTable,
			Columns: []string{experienceusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experienceusage.ApplicationTable,
			Columns: []string{experienceusage.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.application_experience_usages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CoverLetterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experienceusage.CoverLetterTable,
			Columns: []string{experienceusage.CoverLetterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coverletter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cover_letter_experience_usages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExperienceUsageCreateBulk is the builder for creating many ExperienceUsage entities in bulk.
type ExperienceUsageCreateBulk struct {
	config
	err      error
	builders []*ExperienceUsageCreate
}

// Save creates the ExperienceUsage entities in the database.
func (_c *ExperienceUsageCreateBulk) Save(ctx context.Context) ([]*ExperienceUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExperienceUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExperienceUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExperienceUsageCreateBulk) SaveX(ctx context.Context) []*ExperienceUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExperienceUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExperienceUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
