// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experiencetag"
	"github.com/coby/colight/apps/backend/ent/experienceusage"
	"github.com/coby/colight/apps/backend/ent/experienceweapon"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// ExperienceUpdate is the builder for updating Experience entities.
type ExperienceUpdate struct {
	config
	hooks    []Hook
	mutation *ExperienceMutation
}

// Where appends a list predicates to the ExperienceUpdate builder.
func (_u *ExperienceUpdate) Where(ps ...predicate.Experience) *ExperienceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExperienceUpdate) SetUpdatedAt(v time.Time) *ExperienceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExperienceUpdate) SetUserID(v uuid.UUID) *ExperienceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableUserID(v *uuid.UUID) *ExperienceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ExperienceUpdate) SetTitle(v string) *ExperienceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableTitle(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ExperienceUpdate) SetCategory(v string) *ExperienceUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableCategory(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ExperienceUpdate) ClearCategory() *ExperienceUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ExperienceUpdate) SetPeriodStart(v time.Time) *ExperienceUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillablePeriodStart(v *time.Time) *ExperienceUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// ClearPeriodStart clears the value of the "period_start" field.
func (_u *ExperienceUpdate) ClearPeriodStart() *ExperienceUpdate {
	_u.mutation.ClearPeriodStart()
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ExperienceUpdate) SetPeriodEnd(v time.Time) *ExperienceUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillablePeriodEnd(v *time.Time) *ExperienceUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// ClearPeriodEnd clears the value of the "period_end" field.
func (_u *ExperienceUpdate) ClearPeriodEnd() *ExperienceUpdate {
	_u.mutation.ClearPeriodEnd()
	return _u
}

// SetRole sets the "role" field.
func (_u *ExperienceUpdate) SetRole(v string) *ExperienceUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableRole(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "role" field.
func (_u *ExperienceUpdate) ClearRole() *ExperienceUpdate {
	_u.mutation.ClearRole()
	return _u
}

// SetContent sets the "content" field.
func (_u *ExperienceUpdate) SetContent(v string) *ExperienceUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableContent(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ExperienceUpdate) SetResult(v string) *ExperienceUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableResult(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *ExperienceUpdate) ClearResult() *ExperienceUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetStarSituation sets the "star_situation" field.
func (_u *ExperienceUpdate) SetStarSituation(v string) *ExperienceUpdate {
	_u.mutation.SetStarSituation(v)
	return _u
}

// SetNillableStarSituation sets the "star_situation" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableStarSituation(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetStarSituation(*v)
	}
	return _u
}

// ClearStarSituation clears the value of the "star_situation" field.
func (_u *ExperienceUpdate) ClearStarSituation() *ExperienceUpdate {
	_u.mutation.ClearStarSituation()
	return _u
}

// SetStarTask sets the "star_task" field.
func (_u *ExperienceUpdate) SetStarTask(v string) *ExperienceUpdate {
	_u.mutation.SetStarTask(v)
	return _u
}

// SetNillableStarTask sets the "star_task" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableStarTask(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetStarTask(*v)
	}
	return _u
}

// ClearStarTask clears the value of the "star_task" field.
func (_u *ExperienceUpdate) ClearStarTask() *ExperienceUpdate {
	_u.mutation.ClearStarTask()
	return _u
}

// SetStarAction sets the "star_action" field.
func (_u *ExperienceUpdate) SetStarAction(v string) *ExperienceUpdate {
	_u.mutation.SetStarAction(v)
	return _u
}

// SetNillableStarAction sets the "star_action" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableStarAction(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetStarAction(*v)
	}
	return _u
}

// ClearStarAction clears the value of the "star_action" field.
func (_u *ExperienceUpdate) ClearStarAction() *ExperienceUpdate {
	_u.mutation.ClearStarAction()
	return _u
}

// SetStarResult sets the "star_result" field.
func (_u *ExperienceUpdate) SetStarResult(v string) *ExperienceUpdate {
	_u.mutation.SetStarResult(v)
	return _u
}

// SetNillableStarResult sets the "star_result" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableStarResult(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetStarResult(*v)
	}
	return _u
}

// ClearStarResult clears the value of the "star_result" field.
func (_u *ExperienceUpdate) ClearStarResult() *ExperienceUpdate {
	_u.mutation.ClearStarResult()
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *ExperienceUpdate) SetKeywords(v []string) *ExperienceUpdate {
	_u.mutation.SetKeywords(v)
	return _u
}

// AppendKeywords appends value to the "keywords" field.
func (_u *ExperienceUpdate) AppendKeywords(v []string) *ExperienceUpdate {
	_u.mutation.AppendKeywords(v)
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *ExperienceUpdate) ClearKeywords() *ExperienceUpdate {
	_u.mutation.ClearKeywords()
	return _u
}

// SetSource sets the "source" field.
func (_u *ExperienceUpdate) SetSource(v string) *ExperienceUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableSource(v *string) *ExperienceUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsArchived sets the "is_archived" field.
func (_u *ExperienceUpdate) SetIsArchived(v bool) *ExperienceUpdate {
	_u.mutation.SetIsArchived(v)
	return _u
}

// SetNillableIsArchived sets the "is_archived" field if the given value is not nil.
func (_u *ExperienceUpdate) SetNillableIsArchived(v *bool) *ExperienceUpdate {
	if v != nil {
		_u.SetIsArchived(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_u *ExperienceUpdate) SetUser(v *UserProfile) *ExperienceUpdate {
	return _u.SetUserID(v.ID)
}

// AddTagIDs adds the "tags" edge to the ExperienceTag entity by IDs.
func (_u *ExperienceUpdate) AddTagIDs(ids ...uuid.UUID) *ExperienceUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the ExperienceTag entity.
func (_u *ExperienceUpdate) AddTags(v ...*ExperienceTag) *ExperienceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddWeaponIDs adds the "weapons" edge to the ExperienceWeapon entity by IDs.
func (_u *ExperienceUpdate) AddWeaponIDs(ids ...uuid.UUID) *ExperienceUpdate {
	_u.mutation.AddWeaponIDs(ids...)
	return _u
}

// AddWeapons adds the "weapons" edges to the ExperienceWeapon entity.
func (_u *ExperienceUpdate) AddWeapons(v ...*ExperienceWeapon) *ExperienceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWeaponIDs(ids...)
}

// AddUsageIDs adds the "usages" edge to the ExperienceUsage entity by IDs.
func (_u *ExperienceUpdate) AddUsageIDs(ids ...uuid.UUID) *ExperienceUpdate {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the ExperienceUsage entity.
func (_u *ExperienceUpdate) AddUsages(v ...*ExperienceUsage) *ExperienceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the ExperienceMutation object of the builder.
func (_u *ExperienceUpdate) Mutation() *ExperienceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the UserProfile entity.
func (_u *ExperienceUpdate) ClearUser() *ExperienceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTags clears all "tags" edges to the ExperienceTag entity.
func (_u *ExperienceUpdate) ClearTags() *ExperienceUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to ExperienceTag entities by IDs.
func (_u *ExperienceUpdate) RemoveTagIDs(ids ...uuid.UUID) *ExperienceUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to ExperienceTag entities.
func (_u *ExperienceUpdate) RemoveTags(v ...*ExperienceTag) *ExperienceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearWeapons clears all "weapons" edges to the ExperienceWeapon entity.
func (_u *ExperienceUpdate) ClearWeapons() *ExperienceUpdate {
	_u.mutation.ClearWeapons()
	return _u
}

// RemoveWeaponIDs removes the "weapons" edge to ExperienceWeapon entities by IDs.
func (_u *ExperienceUpdate) RemoveWeaponIDs(ids ...uuid.UUID) *ExperienceUpdate {
	_u.mutation.RemoveWeaponIDs(ids...)
	return _u
}

// RemoveWeapons removes "weapons" edges to ExperienceWeapon entities.
func (_u *ExperienceUpdate) RemoveWeapons(v ...*ExperienceWeapon) *ExperienceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWeaponIDs(ids...)
}

// ClearUsages clears all "usages" edges to the ExperienceUsage entity.
func (_u *ExperienceUpdate) ClearUsages() *ExperienceUpdate {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to ExperienceUsage entities by IDs.
func (_u *ExperienceUpdate) RemoveUsageIDs(ids ...uuid.UUID) *ExperienceUpdate {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to ExperienceUsage entities.
func (_u *ExperienceUpdate) RemoveUsages(v ...*ExperienceUsage) *ExperienceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExperienceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExperienceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExperienceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := experience.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := experience.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Experience.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := experience.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Experience.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := experience.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Experience.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := experience.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Experience.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := experience.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Experience.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Experience.user"`)
	}
	return nil
}

func (_u *ExperienceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experience.Table, experience.Columns, sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(experience.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(experience.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(experience.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(experience.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(experience.FieldPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.PeriodStartCleared() {
		_spec.ClearField(experience.FieldPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(experience.FieldPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.PeriodEndCleared() {
		_spec.ClearField(experience.FieldPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(experience.FieldRole, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(experience.FieldRole, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(experience.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(experience.FieldResult, field.TypeString, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(experience.FieldResult, field.TypeString)
	}
	if value, ok := _u.mutation.StarSituation(); ok {
		_spec.SetField(experience.FieldStarSituation, field.TypeString, value)
	}
	if _u.mutation.StarSituationCleared() {
		_spec.ClearField(experience.FieldStarSituation, field.TypeString)
	}
	if value, ok := _u.mutation.StarTask(); ok {
		_spec.SetField(experience.FieldStarTask, field.TypeString, value)
	}
	if _u.mutation.StarTaskCleared() {
		_spec.ClearField(experience.FieldStarTask, field.TypeString)
	}
	if value, ok := _u.mutation.StarAction(); ok {
		_spec.SetField(experience.FieldStarAction, field.TypeString, value)
	}
	if _u.mutation.StarActionCleared() {
		_spec.ClearField(experience.FieldStarAction, field.TypeString)
	}
	if value, ok := _u.mutation.StarResult(); ok {
		_spec.SetField(experience.FieldStarResult, field.TypeString, value)
	}
	if _u.mutation.StarResultCleared() {
		_spec.ClearField(experience.FieldStarResult, field.TypeString)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(experience.FieldKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, experience.FieldKeywords, value)
		})
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(experience.FieldKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(experience.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsArchived(); ok {
		_spec.SetField(experience.FieldIsArchived, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WeaponsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWeaponsIDs(); len(nodes) > 0 && !_u.mutation.WeaponsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WeaponsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experience.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExperienceUpdateOne is the builder for updating a single Experience entity.
type ExperienceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExperienceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExperienceUpdateOne) SetUpdatedAt(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExperienceUpdateOne) SetUserID(v uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableUserID(v *uuid.UUID) *ExperienceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ExperienceUpdateOne) SetTitle(v string) *ExperienceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableTitle(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ExperienceUpdateOne) SetCategory(v string) *ExperienceUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableCategory(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ExperienceUpdateOne) ClearCategory() *ExperienceUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ExperienceUpdateOne) SetPeriodStart(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillablePeriodStart(v *time.Time) *ExperienceUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// ClearPeriodStart clears the value of the "period_start" field.
func (_u *ExperienceUpdateOne) ClearPeriodStart() *ExperienceUpdateOne {
	_u.mutation.ClearPeriodStart()
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ExperienceUpdateOne) SetPeriodEnd(v time.Time) *ExperienceUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillablePeriodEnd(v *time.Time) *ExperienceUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// ClearPeriodEnd clears the value of the "period_end" field.
func (_u *ExperienceUpdateOne) ClearPeriodEnd() *ExperienceUpdateOne {
	_u.mutation.ClearPeriodEnd()
	return _u
}

// SetRole sets the "role" field.
func (_u *ExperienceUpdateOne) SetRole(v string) *ExperienceUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableRole(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "role" field.
func (_u *ExperienceUpdateOne) ClearRole() *ExperienceUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// SetContent sets the "content" field.
func (_u *ExperienceUpdateOne) SetContent(v string) *ExperienceUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableContent(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *ExperienceUpdateOne) SetResult(v string) *ExperienceUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableResult(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *ExperienceUpdateOne) ClearResult() *ExperienceUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetStarSituation sets the "star_situation" field.
func (_u *ExperienceUpdateOne) SetStarSituation(v string) *ExperienceUpdateOne {
	_u.mutation.SetStarSituation(v)
	return _u
}

// SetNillableStarSituation sets the "star_situation" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableStarSituation(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetStarSituation(*v)
	}
	return _u
}

// ClearStarSituation clears the value of the "star_situation" field.
func (_u *ExperienceUpdateOne) ClearStarSituation() *ExperienceUpdateOne {
	_u.mutation.ClearStarSituation()
	return _u
}

// SetStarTask sets the "star_task" field.
func (_u *ExperienceUpdateOne) SetStarTask(v string) *ExperienceUpdateOne {
	_u.mutation.SetStarTask(v)
	return _u
}

// SetNillableStarTask sets the "star_task" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableStarTask(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetStarTask(*v)
	}
	return _u
}

// ClearStarTask clears the value of the "star_task" field.
func (_u *ExperienceUpdateOne) ClearStarTask() *ExperienceUpdateOne {
	_u.mutation.ClearStarTask()
	return _u
}

// SetStarAction sets the "star_action" field.
func (_u *ExperienceUpdateOne) SetStarAction(v string) *ExperienceUpdateOne {
	_u.mutation.SetStarAction(v)
	return _u
}

// SetNillableStarAction sets the "star_action" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableStarAction(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetStarAction(*v)
	}
	return _u
}

// ClearStarAction clears the value of the "star_action" field.
func (_u *ExperienceUpdateOne) ClearStarAction() *ExperienceUpdateOne {
	_u.mutation.ClearStarAction()
	return _u
}

// SetStarResult sets the "star_result" field.
func (_u *ExperienceUpdateOne) SetStarResult(v string) *ExperienceUpdateOne {
	_u.mutation.SetStarResult(v)
	return _u
}

// SetNillableStarResult sets the "star_result" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableStarResult(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetStarResult(*v)
	}
	return _u
}

// ClearStarResult clears the value of the "star_result" field.
func (_u *ExperienceUpdateOne) ClearStarResult() *ExperienceUpdateOne {
	_u.mutation.ClearStarResult()
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *ExperienceUpdateOne) SetKeywords(v []string) *ExperienceUpdateOne {
	_u.mutation.SetKeywords(v)
	return _u
}

// AppendKeywords appends value to the "keywords" field.
func (_u *ExperienceUpdateOne) AppendKeywords(v []string) *ExperienceUpdateOne {
	_u.mutation.AppendKeywords(v)
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *ExperienceUpdateOne) ClearKeywords() *ExperienceUpdateOne {
	_u.mutation.ClearKeywords()
	return _u
}

// SetSource sets the "source" field.
func (_u *ExperienceUpdateOne) SetSource(v string) *ExperienceUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableSource(v *string) *ExperienceUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIsArchived sets the "is_archived" field.
func (_u *ExperienceUpdateOne) SetIsArchived(v bool) *ExperienceUpdateOne {
	_u.mutation.SetIsArchived(v)
	return _u
}

// SetNillableIsArchived sets the "is_archived" field if the given value is not nil.
func (_u *ExperienceUpdateOne) SetNillableIsArchived(v *bool) *ExperienceUpdateOne {
	if v != nil {
		_u.SetIsArchived(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_u *ExperienceUpdateOne) SetUser(v *UserProfile) *ExperienceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddTagIDs adds the "tags" edge to the ExperienceTag entity by IDs.
func (_u *ExperienceUpdateOne) AddTagIDs(ids ...uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the ExperienceTag entity.
func (_u *ExperienceUpdateOne) AddTags(v ...*ExperienceTag) *ExperienceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddWeaponIDs adds the "weapons" edge to the ExperienceWeapon entity by IDs.
func (_u *ExperienceUpdateOne) AddWeaponIDs(ids ...uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.AddWeaponIDs(ids...)
	return _u
}

// AddWeapons adds the "weapons" edges to the ExperienceWeapon entity.
func (_u *ExperienceUpdateOne) AddWeapons(v ...*ExperienceWeapon) *ExperienceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWeaponIDs(ids...)
}

// AddUsageIDs adds the "usages" edge to the ExperienceUsage entity by IDs.
func (_u *ExperienceUpdateOne) AddUsageIDs(ids ...uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the ExperienceUsage entity.
func (_u *ExperienceUpdateOne) AddUsages(v ...*ExperienceUsage) *ExperienceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the ExperienceMutation object of the builder.
func (_u *ExperienceUpdateOne) Mutation() *ExperienceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the UserProfile entity.
func (_u *ExperienceUpdateOne) ClearUser() *ExperienceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTags clears all "tags" edges to the ExperienceTag entity.
func (_u *ExperienceUpdateOne) ClearTags() *ExperienceUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to ExperienceTag entities by IDs.
func (_u *ExperienceUpdateOne) RemoveTagIDs(ids ...uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to ExperienceTag entities.
func (_u *ExperienceUpdateOne) RemoveTags(v ...*ExperienceTag) *ExperienceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearWeapons clears all "weapons" edges to the ExperienceWeapon entity.
func (_u *ExperienceUpdateOne) ClearWeapons() *ExperienceUpdateOne {
	_u.mutation.ClearWeapons()
	return _u
}

// RemoveWeaponIDs removes the "weapons" edge to ExperienceWeapon entities by IDs.
func (_u *ExperienceUpdateOne) RemoveWeaponIDs(ids ...uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.RemoveWeaponIDs(ids...)
	return _u
}

// RemoveWeapons removes "weapons" edges to ExperienceWeapon entities.
func (_u *ExperienceUpdateOne) RemoveWeapons(v ...*ExperienceWeapon) *ExperienceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWeaponIDs(ids...)
}

// ClearUsages clears all "usages" edges to the ExperienceUsage entity.
func (_u *ExperienceUpdateOne) ClearUsages() *ExperienceUpdateOne {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to ExperienceUsage entities by IDs.
func (_u *ExperienceUpdateOne) RemoveUsageIDs(ids ...uuid.UUID) *ExperienceUpdateOne {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to ExperienceUsage entities.
func (_u *ExperienceUpdateOne) RemoveUsages(v ...*ExperienceUsage) *ExperienceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Where appends a list predicates to the ExperienceUpdate builder.
func (_u *ExperienceUpdateOne) Where(ps ...predicate.Experience) *ExperienceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExperienceUpdateOne) Select(field string, fields ...string) *ExperienceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Experience entity.
func (_u *ExperienceUpdateOne) Save(ctx context.Context) (*Experience, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceUpdateOne) SaveX(ctx context.Context) *Experience {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExperienceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExperienceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := experience.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := experience.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Experience.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := experience.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Experience.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := experience.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Experience.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := experience.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Experience.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := experience.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Experience.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Experience.user"`)
	}
	return nil
}

func (_u *ExperienceUpdateOne) sqlSave(ctx context.Context) (_node *Experience, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experience.Table, experience.Columns, sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Experience.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, experience.FieldID)
		for _, f := range fields {
			if !experience.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != experience.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(experience.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(experience.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(experience.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(experience.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(experience.FieldPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.PeriodStartCleared() {
		_spec.ClearField(experience.FieldPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(experience.FieldPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.PeriodEndCleared() {
		_spec.ClearField(experience.FieldPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(experience.FieldRole, field.TypeString, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(experience.FieldRole, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(experience.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(experience.FieldResult, field.TypeString, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(experience.FieldResult, field.TypeString)
	}
	if value, ok := _u.mutation.StarSituation(); ok {
		_spec.SetField(experience.FieldStarSituation, field.TypeString, value)
	}
	if _u.mutation.StarSituationCleared() {
		_spec.ClearField(experience.FieldStarSituation, field.TypeString)
	}
	if value, ok := _u.mutation.StarTask(); ok {
		_spec.SetField(experience.FieldStarTask, field.TypeString, value)
	}
	if _u.mutation.StarTaskCleared() {
		_spec.ClearField(experience.FieldStarTask, field.TypeString)
	}
	if value, ok := _u.mutation.StarAction(); ok {
		_spec.SetField(experience.FieldStarAction, field.TypeString, value)
	}
	if _u.mutation.StarActionCleared() {
		_spec.ClearField(experience.FieldStarAction, field.TypeString)
	}
	if value, ok := _u.mutation.StarResult(); ok {
		_spec.SetField(experience.FieldStarResult, field.TypeString, value)
	}
	if _u.mutation.StarResultCleared() {
		_spec.ClearField(experience.FieldStarResult, field.TypeString)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(experience.FieldKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, experience.FieldKeywords, value)
		})
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(experience.FieldKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(experience.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsArchived(); ok {
		_spec.SetField(experience.FieldIsArchived, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   experience.UserTable,
			Columns: []string{experience.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.TagsTable,
			Columns: []string{experience.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiencetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WeaponsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWeaponsIDs(); len(nodes) > 0 && !_u.mutation.WeaponsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WeaponsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.WeaponsTable,
			Columns: []string{experience.WeaponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceweapon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   experience.UsagesTable,
			Columns: []string{experience.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Experience{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experience.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
