// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/coby/colight/apps/backend/ent/prompttemplate"
	"github.com/coby/colight/apps/backend/ent/questionpattern"
	"github.com/google/uuid"
)

// QuestionPatternUpdate is the builder for updating QuestionPattern entities.
type QuestionPatternUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionPatternMutation
}

// Where appends a list predicates to the QuestionPatternUpdate builder.
func (_u *QuestionPatternUpdate) Where(ps ...predicate.QuestionPattern) *QuestionPatternUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPatternType sets the "pattern_type" field.
func (_u *QuestionPatternUpdate) SetPatternType(v string) *QuestionPatternUpdate {
	_u.mutation.SetPatternType(v)
	return _u
}

// SetNillablePatternType sets the "pattern_type" field if the given value is not nil.
func (_u *QuestionPatternUpdate) SetNillablePatternType(v *string) *QuestionPatternUpdate {
	if v != nil {
		_u.SetPatternType(*v)
	}
	return _u
}

// SetPatternName sets the "pattern_name" field.
func (_u *QuestionPatternUpdate) SetPatternName(v string) *QuestionPatternUpdate {
	_u.mutation.SetPatternName(v)
	return _u
}

// SetNillablePatternName sets the "pattern_name" field if the given value is not nil.
func (_u *QuestionPatternUpdate) SetNillablePatternName(v *string) *QuestionPatternUpdate {
	if v != nil {
		_u.SetPatternName(*v)
	}
	return _u
}

// SetDetectionKeywords sets the "detection_keywords" field.
func (_u *QuestionPatternUpdate) SetDetectionKeywords(v []string) *QuestionPatternUpdate {
	_u.mutation.SetDetectionKeywords(v)
	return _u
}

// AppendDetectionKeywords appends value to the "detection_keywords" field.
func (_u *QuestionPatternUpdate) AppendDetectionKeywords(v []string) *QuestionPatternUpdate {
	_u.mutation.AppendDetectionKeywords(v)
	return _u
}

// ClearDetectionKeywords clears the value of the "detection_keywords" field.
func (_u *QuestionPatternUpdate) ClearDetectionKeywords() *QuestionPatternUpdate {
	_u.mutation.ClearDetectionKeywords()
	return _u
}

// SetDetectionRegex sets the "detection_regex" field.
func (_u *QuestionPatternUpdate) SetDetectionRegex(v string) *QuestionPatternUpdate {
	_u.mutation.SetDetectionRegex(v)
	return _u
}

// SetNillableDetectionRegex sets the "detection_regex" field if the given value is not nil.
func (_u *QuestionPatternUpdate) SetNillableDetectionRegex(v *string) *QuestionPatternUpdate {
	if v != nil {
		_u.SetDetectionRegex(*v)
	}
	return _u
}

// ClearDetectionRegex clears the value of the "detection_regex" field.
func (_u *QuestionPatternUpdate) ClearDetectionRegex() *QuestionPatternUpdate {
	_u.mutation.ClearDetectionRegex()
	return _u
}

// SetPrimaryWeapons sets the "primary_weapons" field.
func (_u *QuestionPatternUpdate) SetPrimaryWeapons(v []string) *QuestionPatternUpdate {
	_u.mutation.SetPrimaryWeapons(v)
	return _u
}

// AppendPrimaryWeapons appends value to the "primary_weapons" field.
func (_u *QuestionPatternUpdate) AppendPrimaryWeapons(v []string) *QuestionPatternUpdate {
	_u.mutation.AppendPrimaryWeapons(v)
	return _u
}

// ClearPrimaryWeapons clears the value of the "primary_weapons" field.
func (_u *QuestionPatternUpdate) ClearPrimaryWeapons() *QuestionPatternUpdate {
	_u.mutation.ClearPrimaryWeapons()
	return _u
}

// SetSecondaryWeapons sets the "secondary_weapons" field.
func (_u *QuestionPatternUpdate) SetSecondaryWeapons(v []string) *QuestionPatternUpdate {
	_u.mutation.SetSecondaryWeapons(v)
	return _u
}

// AppendSecondaryWeapons appends value to the "secondary_weapons" field.
func (_u *QuestionPatternUpdate) AppendSecondaryWeapons(v []string) *QuestionPatternUpdate {
	_u.mutation.AppendSecondaryWeapons(v)
	return _u
}

// ClearSecondaryWeapons clears the value of the "secondary_weapons" field.
func (_u *QuestionPatternUpdate) ClearSecondaryWeapons() *QuestionPatternUpdate {
	_u.mutation.ClearSecondaryWeapons()
	return _u
}

// SetWritingGuide sets the "writing_guide" field.
func (_u *QuestionPatternUpdate) SetWritingGuide(v map[string]interface{}) *QuestionPatternUpdate {
	_u.mutation.SetWritingGuide(v)
	return _u
}

// ClearWritingGuide clears the value of the "writing_guide" field.
func (_u *QuestionPatternUpdate) ClearWritingGuide() *QuestionPatternUpdate {
	_u.mutation.ClearWritingGuide()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *QuestionPatternUpdate) SetDisplayOrder(v int) *QuestionPatternUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *QuestionPatternUpdate) SetNillableDisplayOrder(v *int) *QuestionPatternUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *QuestionPatternUpdate) AddDisplayOrder(v int) *QuestionPatternUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *QuestionPatternUpdate) SetIsActive(v bool) *QuestionPatternUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *QuestionPatternUpdate) SetNillableIsActive(v *bool) *QuestionPatternUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCoachingPromptID sets the "coaching_prompt" edge to the PromptTemplate entity by ID.
func (_u *QuestionPatternUpdate) SetCoachingPromptID(id uuid.UUID) *QuestionPatternUpdate {
	_u.mutation.SetCoachingPromptID(id)
	return _u
}

// SetNillableCoachingPromptID sets the "coaching_prompt" edge to the PromptTemplate entity by ID if the given value is not nil.
func (_u *QuestionPatternUpdate) SetNillableCoachingPromptID(id *uuid.UUID) *QuestionPatternUpdate {
	if id != nil {
		_u = _u.SetCoachingPromptID(*id)
	}
	return _u
}

// SetCoachingPrompt sets the "coaching_prompt" edge to the PromptTemplate entity.
func (_u *QuestionPatternUpdate) SetCoachingPrompt(v *PromptTemplate) *QuestionPatternUpdate {
	return _u.SetCoachingPromptID(v.ID)
}

// Mutation returns the QuestionPatternMutation object of the builder.
func (_u *QuestionPatternUpdate) Mutation() *QuestionPatternMutation {
	return _u.mutation
}

// ClearCoachingPrompt clears the "coaching_prompt" edge to the PromptTemplate entity.
func (_u *QuestionPatternUpdate) ClearCoachingPrompt() *QuestionPatternUpdate {
	_u.mutation.ClearCoachingPrompt()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuestionPatternUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionPatternUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuestionPatternUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionPatternUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuestionPatternUpdate) check() error {
	if v, ok := _u.mutation.PatternType(); ok {
		if err := questionpattern.PatternTypeValidator(v); err != nil {
			return &ValidationError{Name: "pattern_type", err: fmt.Errorf(`ent: validator failed for field "QuestionPattern.pattern_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PatternName(); ok {
		if err := questionpattern.PatternNameValidator(v); err != nil {
			return &ValidationError{Name: "pattern_name", err: fmt.Errorf(`ent: validator failed for field "QuestionPattern.pattern_name": %w`, err)}
		}
	}
	return nil
}

func (_u *QuestionPatternUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(questionpattern.Table, questionpattern.Columns, sqlgraph.NewFieldSpec(questionpattern.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PatternType(); ok {
		_spec.SetField(questionpattern.FieldPatternType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PatternName(); ok {
		_spec.SetField(questionpattern.FieldPatternName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectionKeywords(); ok {
		_spec.SetField(questionpattern.FieldDetectionKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetectionKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, questionpattern.FieldDetectionKeywords, value)
		})
	}
	if _u.mutation.DetectionKeywordsCleared() {
		_spec.ClearField(questionpattern.FieldDetectionKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.DetectionRegex(); ok {
		_spec.SetField(questionpattern.FieldDetectionRegex, field.TypeString, value)
	}
	if _u.mutation.DetectionRegexCleared() {
		_spec.ClearField(questionpattern.FieldDetectionRegex, field.TypeString)
	}
	if value, ok := _u.mutation.PrimaryWeapons(); ok {
		_spec.SetField(questionpattern.FieldPrimaryWeapons, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPrimaryWeapons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, questionpattern.FieldPrimaryWeapons, value)
		})
	}
	if _u.mutation.PrimaryWeaponsCleared() {
		_spec.ClearField(questionpattern.FieldPrimaryWeapons, field.TypeJSON)
	}
	if value, ok := _u.mutation.SecondaryWeapons(); ok {
		_spec.SetField(questionpattern.FieldSecondaryWeapons, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSecondaryWeapons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, questionpattern.FieldSecondaryWeapons, value)
		})
	}
	if _u.mutation.SecondaryWeaponsCleared() {
		_spec.ClearField(questionpattern.FieldSecondaryWeapons, field.TypeJSON)
	}
	if value, ok := _u.mutation.WritingGuide(); ok {
		_spec.SetField(questionpattern.FieldWritingGuide, field.TypeJSON, value)
	}
	if _u.mutation.WritingGuideCleared() {
		_spec.ClearField(questionpattern.FieldWritingGuide, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(questionpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(questionpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(questionpattern.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.CoachingPromptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionpattern.CoachingPromptTable,
			Columns: []string{questionpattern.CoachingPromptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoachingPromptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionpattern.CoachingPromptTable,
			Columns: []string{questionpattern.CoachingPromptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{questionpattern.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuestionPatternUpdateOne is the builder for updating a single QuestionPattern entity.
type QuestionPatternUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionPatternMutation
}

// SetPatternType sets the "pattern_type" field.
func (_u *QuestionPatternUpdateOne) SetPatternType(v string) *QuestionPatternUpdateOne {
	_u.mutation.SetPatternType(v)
	return _u
}

// SetNillablePatternType sets the "pattern_type" field if the given value is not nil.
func (_u *QuestionPatternUpdateOne) SetNillablePatternType(v *string) *QuestionPatternUpdateOne {
	if v != nil {
		_u.SetPatternType(*v)
	}
	return _u
}

// SetPatternName sets the "pattern_name" field.
func (_u *QuestionPatternUpdateOne) SetPatternName(v string) *QuestionPatternUpdateOne {
	_u.mutation.SetPatternName(v)
	return _u
}

// SetNillablePatternName sets the "pattern_name" field if the given value is not nil.
func (_u *QuestionPatternUpdateOne) SetNillablePatternName(v *string) *QuestionPatternUpdateOne {
	if v != nil {
		_u.SetPatternName(*v)
	}
	return _u
}

// SetDetectionKeywords sets the "detection_keywords" field.
func (_u *QuestionPatternUpdateOne) SetDetectionKeywords(v []string) *QuestionPatternUpdateOne {
	_u.mutation.SetDetectionKeywords(v)
	return _u
}

// AppendDetectionKeywords appends value to the "detection_keywords" field.
func (_u *QuestionPatternUpdateOne) AppendDetectionKeywords(v []string) *QuestionPatternUpdateOne {
	_u.mutation.AppendDetectionKeywords(v)
	return _u
}

// ClearDetectionKeywords clears the value of the "detection_keywords" field.
func (_u *QuestionPatternUpdateOne) ClearDetectionKeywords() *QuestionPatternUpdateOne {
	_u.mutation.ClearDetectionKeywords()
	return _u
}

// SetDetectionRegex sets the "detection_regex" field.
func (_u *QuestionPatternUpdateOne) SetDetectionRegex(v string) *QuestionPatternUpdateOne {
	_u.mutation.SetDetectionRegex(v)
	return _u
}

// SetNillableDetectionRegex sets the "detection_regex" field if the given value is not nil.
func (_u *QuestionPatternUpdateOne) SetNillableDetectionRegex(v *string) *QuestionPatternUpdateOne {
	if v != nil {
		_u.SetDetectionRegex(*v)
	}
	return _u
}

// ClearDetectionRegex clears the value of the "detection_regex" field.
func (_u *QuestionPatternUpdateOne) ClearDetectionRegex() *QuestionPatternUpdateOne {
	_u.mutation.ClearDetectionRegex()
	return _u
}

// SetPrimaryWeapons sets the "primary_weapons" field.
func (_u *QuestionPatternUpdateOne) SetPrimaryWeapons(v []string) *QuestionPatternUpdateOne {
	_u.mutation.SetPrimaryWeapons(v)
	return _u
}

// AppendPrimaryWeapons appends value to the "primary_weapons" field.
func (_u *QuestionPatternUpdateOne) AppendPrimaryWeapons(v []string) *QuestionPatternUpdateOne {
	_u.mutation.AppendPrimaryWeapons(v)
	return _u
}

// ClearPrimaryWeapons clears the value of the "primary_weapons" field.
func (_u *QuestionPatternUpdateOne) ClearPrimaryWeapons() *QuestionPatternUpdateOne {
	_u.mutation.ClearPrimaryWeapons()
	return _u
}

// SetSecondaryWeapons sets the "secondary_weapons" field.
func (_u *QuestionPatternUpdateOne) SetSecondaryWeapons(v []string) *QuestionPatternUpdateOne {
	_u.mutation.SetSecondaryWeapons(v)
	return _u
}

// AppendSecondaryWeapons appends value to the "secondary_weapons" field.
func (_u *QuestionPatternUpdateOne) AppendSecondaryWeapons(v []string) *QuestionPatternUpdateOne {
	_u.mutation.AppendSecondaryWeapons(v)
	return _u
}

// ClearSecondaryWeapons clears the value of the "secondary_weapons" field.
func (_u *QuestionPatternUpdateOne) ClearSecondaryWeapons() *QuestionPatternUpdateOne {
	_u.mutation.ClearSecondaryWeapons()
	return _u
}

// SetWritingGuide sets the "writing_guide" field.
func (_u *QuestionPatternUpdateOne) SetWritingGuide(v map[string]interface{}) *QuestionPatternUpdateOne {
	_u.mutation.SetWritingGuide(v)
	return _u
}

// ClearWritingGuide clears the value of the "writing_guide" field.
func (_u *QuestionPatternUpdateOne) ClearWritingGuide() *QuestionPatternUpdateOne {
	_u.mutation.ClearWritingGuide()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *QuestionPatternUpdateOne) SetDisplayOrder(v int) *QuestionPatternUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *QuestionPatternUpdateOne) SetNillableDisplayOrder(v *int) *QuestionPatternUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *QuestionPatternUpdateOne) AddDisplayOrder(v int) *QuestionPatternUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *QuestionPatternUpdateOne) SetIsActive(v bool) *QuestionPatternUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *QuestionPatternUpdateOne) SetNillableIsActive(v *bool) *QuestionPatternUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCoachingPromptID sets the "coaching_prompt" edge to the PromptTemplate entity by ID.
func (_u *QuestionPatternUpdateOne) SetCoachingPromptID(id uuid.UUID) *QuestionPatternUpdateOne {
	_u.mutation.SetCoachingPromptID(id)
	return _u
}

// SetNillableCoachingPromptID sets the "coaching_prompt" edge to the PromptTemplate entity by ID if the given value is not nil.
func (_u *QuestionPatternUpdateOne) SetNillableCoachingPromptID(id *uuid.UUID) *QuestionPatternUpdateOne {
	if id != nil {
		_u = _u.SetCoachingPromptID(*id)
	}
	return _u
}

// SetCoachingPrompt sets the "coaching_prompt" edge to the PromptTemplate entity.
func (_u *QuestionPatternUpdateOne) SetCoachingPrompt(v *PromptTemplate) *QuestionPatternUpdateOne {
	return _u.SetCoachingPromptID(v.ID)
}

// Mutation returns the QuestionPatternMutation object of the builder.
func (_u *QuestionPatternUpdateOne) Mutation() *QuestionPatternMutation {
	return _u.mutation
}

// ClearCoachingPrompt clears the "coaching_prompt" edge to the PromptTemplate entity.
func (_u *QuestionPatternUpdateOne) ClearCoachingPrompt() *QuestionPatternUpdateOne {
	_u.mutation.ClearCoachingPrompt()
	return _u
}

// Where appends a list predicates to the QuestionPatternUpdate builder.
func (_u *QuestionPatternUpdateOne) Where(ps ...predicate.QuestionPattern) *QuestionPatternUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuestionPatternUpdateOne) Select(field string, fields ...string) *QuestionPatternUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuestionPattern entity.
func (_u *QuestionPatternUpdateOne) Save(ctx context.Context) (*QuestionPattern, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionPatternUpdateOne) SaveX(ctx context.Context) *QuestionPattern {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuestionPatternUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionPatternUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuestionPatternUpdateOne) check() error {
	if v, ok := _u.mutation.PatternType(); ok {
		if err := questionpattern.PatternTypeValidator(v); err != nil {
			return &ValidationError{Name: "pattern_type", err: fmt.Errorf(`ent: validator failed for field "QuestionPattern.pattern_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PatternName(); ok {
		if err := questionpattern.PatternNameValidator(v); err != nil {
			return &ValidationError{Name: "pattern_name", err: fmt.Errorf(`ent: validator failed for field "QuestionPattern.pattern_name": %w`, err)}
		}
	}
	return nil
}

func (_u *QuestionPatternUpdateOne) sqlSave(ctx context.Context) (_node *QuestionPattern, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(questionpattern.Table, questionpattern.Columns, sqlgraph.NewFieldSpec(questionpattern.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuestionPattern.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questionpattern.FieldID)
		for _, f := range fields {
			if !questionpattern.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != questionpattern.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PatternType(); ok {
		_spec.SetField(questionpattern.FieldPatternType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PatternName(); ok {
		_spec.SetField(questionpattern.FieldPatternName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectionKeywords(); ok {
		_spec.SetField(questionpattern.FieldDetectionKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetectionKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, questionpattern.FieldDetectionKeywords, value)
		})
	}
	if _u.mutation.DetectionKeywordsCleared() {
		_spec.ClearField(questionpattern.FieldDetectionKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.DetectionRegex(); ok {
		_spec.SetField(questionpattern.FieldDetectionRegex, field.TypeString, value)
	}
	if _u.mutation.DetectionRegexCleared() {
		_spec.ClearField(questionpattern.FieldDetectionRegex, field.TypeString)
	}
	if value, ok := _u.mutation.PrimaryWeapons(); ok {
		_spec.SetField(questionpattern.FieldPrimaryWeapons, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPrimaryWeapons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, questionpattern.FieldPrimaryWeapons, value)
		})
	}
	if _u.mutation.PrimaryWeaponsCleared() {
		_spec.ClearField(questionpattern.FieldPrimaryWeapons, field.TypeJSON)
	}
	if value, ok := _u.mutation.SecondaryWeapons(); ok {
		_spec.SetField(questionpattern.FieldSecondaryWeapons, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSecondaryWeapons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, questionpattern.FieldSecondaryWeapons, value)
		})
	}
	if _u.mutation.SecondaryWeaponsCleared() {
		_spec.ClearField(questionpattern.FieldSecondaryWeapons, field.TypeJSON)
	}
	if value, ok := _u.mutation.WritingGuide(); ok {
		_spec.SetField(questionpattern.FieldWritingGuide, field.TypeJSON, value)
	}
	if _u.mutation.WritingGuideCleared() {
		_spec.ClearField(questionpattern.FieldWritingGuide, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(questionpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(questionpattern.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(questionpattern.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.CoachingPromptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionpattern.CoachingPromptTable,
			Columns: []string{questionpattern.CoachingPromptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoachingPromptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionpattern.CoachingPromptTable,
			Columns: []string{questionpattern.CoachingPromptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuestionPattern{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{questionpattern.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
