// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/coby/colight/apps/backend/ent/quotahitevent"
	"github.com/coby/colight/apps/backend/ent/usagelog"
	"github.com/google/uuid"
)

// QuotaHitEventUpdate is the builder for updating QuotaHitEvent entities.
type QuotaHitEventUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaHitEventMutation
}

// Where appends a list predicates to the QuotaHitEventUpdate builder.
func (_u *QuotaHitEventUpdate) Where(ps ...predicate.QuotaHitEvent) *QuotaHitEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *QuotaHitEventUpdate) SetProvider(v string) *QuotaHitEventUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *QuotaHitEventUpdate) SetNillableProvider(v *string) *QuotaHitEventUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *QuotaHitEventUpdate) SetModel(v string) *QuotaHitEventUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *QuotaHitEventUpdate) SetNillableModel(v *string) *QuotaHitEventUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetFeature sets the "feature" field.
func (_u *QuotaHitEventUpdate) SetFeature(v string) *QuotaHitEventUpdate {
	_u.mutation.SetFeature(v)
	return _u
}

// SetNillableFeature sets the "feature" field if the given value is not nil.
func (_u *QuotaHitEventUpdate) SetNillableFeature(v *string) *QuotaHitEventUpdate {
	if v != nil {
		_u.SetFeature(*v)
	}
	return _u
}

// ClearFeature clears the value of the "feature" field.
func (_u *QuotaHitEventUpdate) ClearFeature() *QuotaHitEventUpdate {
	_u.mutation.ClearFeature()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *QuotaHitEventUpdate) SetErrorMessage(v string) *QuotaHitEventUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *QuotaHitEventUpdate) SetNillableErrorMessage(v *string) *QuotaHitEventUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *QuotaHitEventUpdate) SetUsageLogID(v uuid.UUID) *QuotaHitEventUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *QuotaHitEventUpdate) SetNillableUsageLogID(v *uuid.UUID) *QuotaHitEventUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *QuotaHitEventUpdate) ClearUsageLogID() *QuotaHitEventUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *QuotaHitEventUpdate) SetUsageLog(v *UsageLog) *QuotaHitEventUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the QuotaHitEventMutation object of the builder.
func (_u *QuotaHitEventUpdate) Mutation() *QuotaHitEventMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *QuotaHitEventUpdate) ClearUsageLog() *QuotaHitEventUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaHitEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaHitEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaHitEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaHitEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaHitEventUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := quotahitevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := quotahitevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Feature(); ok {
		if err := quotahitevent.FeatureValidator(v); err != nil {
			return &ValidationError{Name: "feature", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.feature": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaHitEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotahitevent.Table, quotahitevent.Columns, sqlgraph.NewFieldSpec(quotahitevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(quotahitevent.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(quotahitevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Feature(); ok {
		_spec.SetField(quotahitevent.FieldFeature, field.TypeString, value)
	}
	if _u.mutation.FeatureCleared() {
		_spec.ClearField(quotahitevent.FieldFeature, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(quotahitevent.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotahitevent.UsageLogTable,
			Columns: []string{quotahitevent.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotahitevent.UsageLogTable,
			Columns: []string{quotahitevent.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotahitevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaHitEventUpdateOne is the builder for updating a single QuotaHitEvent entity.
type QuotaHitEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaHitEventMutation
}

// SetProvider sets the "provider" field.
func (_u *QuotaHitEventUpdateOne) SetProvider(v string) *QuotaHitEventUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *QuotaHitEventUpdateOne) SetNillableProvider(v *string) *QuotaHitEventUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *QuotaHitEventUpdateOne) SetModel(v string) *QuotaHitEventUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *QuotaHitEventUpdateOne) SetNillableModel(v *string) *QuotaHitEventUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetFeature sets the "feature" field.
func (_u *QuotaHitEventUpdateOne) SetFeature(v string) *QuotaHitEventUpdateOne {
	_u.mutation.SetFeature(v)
	return _u
}

// SetNillableFeature sets the "feature" field if the given value is not nil.
func (_u *QuotaHitEventUpdateOne) SetNillableFeature(v *string) *QuotaHitEventUpdateOne {
	if v != nil {
		_u.SetFeature(*v)
	}
	return _u
}

// ClearFeature clears the value of the "feature" field.
func (_u *QuotaHitEventUpdateOne) ClearFeature() *QuotaHitEventUpdateOne {
	_u.mutation.ClearFeature()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *QuotaHitEventUpdateOne) SetErrorMessage(v string) *QuotaHitEventUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *QuotaHitEventUpdateOne) SetNillableErrorMessage(v *string) *QuotaHitEventUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *QuotaHitEventUpdateOne) SetUsageLogID(v uuid.UUID) *QuotaHitEventUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *QuotaHitEventUpdateOne) SetNillableUsageLogID(v *uuid.UUID) *QuotaHitEventUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *QuotaHitEventUpdateOne) ClearUsageLogID() *QuotaHitEventUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *QuotaHitEventUpdateOne) SetUsageLog(v *UsageLog) *QuotaHitEventUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the QuotaHitEventMutation object of the builder.
func (_u *QuotaHitEventUpdateOne) Mutation() *QuotaHitEventMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *QuotaHitEventUpdateOne) ClearUsageLog() *QuotaHitEventUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the QuotaHitEventUpdate builder.
func (_u *QuotaHitEventUpdateOne) Where(ps ...predicate.QuotaHitEvent) *QuotaHitEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaHitEventUpdateOne) Select(field string, fields ...string) *QuotaHitEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaHitEvent entity.
func (_u *QuotaHitEventUpdateOne) Save(ctx context.Context) (*QuotaHitEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaHitEventUpdateOne) SaveX(ctx context.Context) *QuotaHitEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaHitEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaHitEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaHitEventUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := quotahitevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := quotahitevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Feature(); ok {
		if err := quotahitevent.FeatureValidator(v); err != nil {
			return &ValidationError{Name: "feature", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.feature": %w`, err)}
		}
	}
	return nil
}

func (_u *QuotaHitEventUpdateOne) sqlSave(ctx context.Context) (_node *QuotaHitEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotahitevent.Table, quotahitevent.Columns, sqlgraph.NewFieldSpec(quotahitevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaHitEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotahitevent.FieldID)
		for _, f := range fields {
			if !quotahitevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotahitevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(quotahitevent.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(quotahitevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Feature(); ok {
		_spec.SetField(quotahitevent.FieldFeature, field.TypeString, value)
	}
	if _u.mutation.FeatureCleared() {
		_spec.ClearField(quotahitevent.FieldFeature, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(quotahitevent.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotahitevent.UsageLogTable,
			Columns: []string{quotahitevent.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotahitevent.UsageLogTable,
			Columns: []string{quotahitevent.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuotaHitEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotahitevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
