// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/quotahitevent"
	"github.com/coby/colight/apps/backend/ent/usagelog"
	"github.com/google/uuid"
)

// QuotaHitEventCreate is the builder for creating a QuotaHitEvent entity.
type QuotaHitEventCreate struct {
	config
	mutation *QuotaHitEventMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuotaHitEventCreate) SetCreatedAt(v time.Time) *QuotaHitEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuotaHitEventCreate) SetNillableCreatedAt(v *time.Time) *QuotaHitEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *QuotaHitEventCreate) SetProvider(v string) *QuotaHitEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *QuotaHitEventCreate) SetModel(v string) *QuotaHitEventCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetFeature sets the "feature" field.
func (_c *QuotaHitEventCreate) SetFeature(v string) *QuotaHitEventCreate {
	_c.mutation.SetFeature(v)
	return _c
}

// SetNillableFeature sets the "feature" field if the given value is not nil.
func (_c *QuotaHitEventCreate) SetNillableFeature(v *string) *QuotaHitEventCreate {
	if v != nil {
		_c.SetFeature(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *QuotaHitEventCreate) SetErrorMessage(v string) *QuotaHitEventCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *QuotaHitEventCreate) SetUsageLogID(v uuid.UUID) *QuotaHitEventCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *QuotaHitEventCreate) SetNillableUsageLogID(v *uuid.UUID) *QuotaHitEventCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuotaHitEventCreate) SetID(v uuid.UUID) *QuotaHitEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QuotaHitEventCreate) SetNillableID(v *uuid.UUID) *QuotaHitEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *QuotaHitEventCreate) SetUsageLog(v *UsageLog) *QuotaHitEventCreate {
	return _c.SetUsageLogID(v.ID)
}

// Mutation returns the QuotaHitEventMutation object of the builder.
func (_c *QuotaHitEventCreate) Mutation() *QuotaHitEventMutation {
	return _c.mutation
}

// Save creates the QuotaHitEvent in the database.
func (_c *QuotaHitEventCreate) Save(ctx context.Context) (*QuotaHitEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuotaHitEventCreate) SaveX(ctx context.Context) *QuotaHitEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaHitEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaHitEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuotaHitEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quotahitevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := quotahitevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuotaHitEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuotaHitEvent.created_at"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "QuotaHitEvent.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := quotahitevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "QuotaHitEvent.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := quotahitevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Feature(); ok {
		if err := quotahitevent.FeatureValidator(v); err != nil {
			return &ValidationError{Name: "feature", err: fmt.Errorf(`ent: validator failed for field "QuotaHitEvent.feature": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "QuotaHitEvent.error_message"`)}
	}
	return nil
}

func (_c *QuotaHitEventCreate) sqlSave(ctx context.Context) (*QuotaHitEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuotaHitEventCreate) createSpec() (*QuotaHitEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &QuotaHitEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quotahitevent.Table, sqlgraph.NewFieldSpec(quotahitevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quotahitevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(quotahitevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(quotahitevent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Feature(); ok {
		_spec.SetField(quotahitevent.FieldFeature, field.TypeString, value)
		_node.Feature = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(quotahitevent.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quotahitevent.UsageLogTable,
			Columns: []string{quotahitevent.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuotaHitEventCreateBulk is the builder for creating many QuotaHitEvent entities in bulk.
type QuotaHitEventCreateBulk struct {
	config
	err      error
	builders []*QuotaHitEventCreate
}

// Save creates the QuotaHitEvent entities in the database.
func (_c *QuotaHitEventCreateBulk) Save(ctx context.Context) ([]*QuotaHitEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuotaHitEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuotaHitEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuotaHitEventCreateBulk) SaveX(ctx context.Context) []*QuotaHitEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuotaHitEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuotaHitEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
