// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/coby/colight/apps/backend/ent/systemconfig"
	"github.com/google/uuid"
)

// SystemConfigUpdate is the builder for updating SystemConfig entities.
type SystemConfigUpdate struct {
	config
	hooks    []Hook
	mutation *SystemConfigMutation
}

// Where appends a list predicates to the SystemConfigUpdate builder.
func (_u *SystemConfigUpdate) Where(ps ...predicate.SystemConfig) *SystemConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemConfigUpdate) SetUpdatedAt(v time.Time) *SystemConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfigKey sets the "config_key" field.
func (_u *SystemConfigUpdate) SetConfigKey(v string) *SystemConfigUpdate {
	_u.mutation.SetConfigKey(v)
	return _u
}

// SetNillableConfigKey sets the "config_key" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableConfigKey(v *string) *SystemConfigUpdate {
	if v != nil {
		_u.SetConfigKey(*v)
	}
	return _u
}

// SetConfigValue sets the "config_value" field.
func (_u *SystemConfigUpdate) SetConfigValue(v string) *SystemConfigUpdate {
	_u.mutation.SetConfigValue(v)
	return _u
}

// SetNillableConfigValue sets the "config_value" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableConfigValue(v *string) *SystemConfigUpdate {
	if v != nil {
		_u.SetConfigValue(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SystemConfigUpdate) SetDescription(v string) *SystemConfigUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableDescription(v *string) *SystemConfigUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SystemConfigUpdate) ClearDescription() *SystemConfigUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *SystemConfigUpdate) SetCategory(v string) *SystemConfigUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableCategory(v *string) *SystemConfigUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetIsSecret sets the "is_secret" field.
func (_u *SystemConfigUpdate) SetIsSecret(v bool) *SystemConfigUpdate {
	_u.mutation.SetIsSecret(v)
	return _u
}

// SetNillableIsSecret sets the "is_secret" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableIsSecret(v *bool) *SystemConfigUpdate {
	if v != nil {
		_u.SetIsSecret(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SystemConfigUpdate) SetUpdatedBy(v uuid.UUID) *SystemConfigUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableUpdatedBy(v *uuid.UUID) *SystemConfigUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SystemConfigUpdate) ClearUpdatedBy() *SystemConfigUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the SystemConfigMutation object of the builder.
func (_u *SystemConfigUpdate) Mutation() *SystemConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemConfigUpdate) check() error {
	if v, ok := _u.mutation.ConfigKey(); ok {
		if err := systemconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.config_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := systemconfig.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := systemconfig.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.category": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemconfig.Table, systemconfig.Columns, sqlgraph.NewFieldSpec(systemconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConfigKey(); ok {
		_spec.SetField(systemconfig.FieldConfigKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigValue(); ok {
		_spec.SetField(systemconfig.FieldConfigValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(systemconfig.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(systemconfig.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(systemconfig.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSecret(); ok {
		_spec.SetField(systemconfig.FieldIsSecret, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(systemconfig.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(systemconfig.FieldUpdatedBy, field.TypeUUID)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemConfigUpdateOne is the builder for updating a single SystemConfig entity.
type SystemConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemConfigUpdateOne) SetUpdatedAt(v time.Time) *SystemConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfigKey sets the "config_key" field.
func (_u *SystemConfigUpdateOne) SetConfigKey(v string) *SystemConfigUpdateOne {
	_u.mutation.SetConfigKey(v)
	return _u
}

// SetNillableConfigKey sets the "config_key" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableConfigKey(v *string) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetConfigKey(*v)
	}
	return _u
}

// SetConfigValue sets the "config_value" field.
func (_u *SystemConfigUpdateOne) SetConfigValue(v string) *SystemConfigUpdateOne {
	_u.mutation.SetConfigValue(v)
	return _u
}

// SetNillableConfigValue sets the "config_value" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableConfigValue(v *string) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetConfigValue(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SystemConfigUpdateOne) SetDescription(v string) *SystemConfigUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableDescription(v *string) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SystemConfigUpdateOne) ClearDescription() *SystemConfigUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *SystemConfigUpdateOne) SetCategory(v string) *SystemConfigUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableCategory(v *string) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetIsSecret sets the "is_secret" field.
func (_u *SystemConfigUpdateOne) SetIsSecret(v bool) *SystemConfigUpdateOne {
	_u.mutation.SetIsSecret(v)
	return _u
}

// SetNillableIsSecret sets the "is_secret" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableIsSecret(v *bool) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetIsSecret(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SystemConfigUpdateOne) SetUpdatedBy(v uuid.UUID) *SystemConfigUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SystemConfigUpdateOne) ClearUpdatedBy() *SystemConfigUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the SystemConfigMutation object of the builder.
func (_u *SystemConfigUpdateOne) Mutation() *SystemConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemConfigUpdate builder.
func (_u *SystemConfigUpdateOne) Where(ps ...predicate.SystemConfig) *SystemConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemConfigUpdateOne) Select(field string, fields ...string) *SystemConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemConfig entity.
func (_u *SystemConfigUpdateOne) Save(ctx context.Context) (*SystemConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemConfigUpdateOne) SaveX(ctx context.Context) *SystemConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemConfigUpdateOne) check() error {
	if v, ok := _u.mutation.ConfigKey(); ok {
		if err := systemconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.config_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := systemconfig.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := systemconfig.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.category": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemConfigUpdateOne) sqlSave(ctx context.Context) (_node *SystemConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemconfig.Table, systemconfig.Columns, sqlgraph.NewFieldSpec(systemconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemconfig.FieldID)
		for _, f := range fields {
			if !systemconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConfigKey(); ok {
		_spec.SetField(systemconfig.FieldConfigKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigValue(); ok {
		_spec.SetField(systemconfig.FieldConfigValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(systemconfig.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(systemconfig.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(systemconfig.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSecret(); ok {
		_spec.SetField(systemconfig.FieldIsSecret, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(systemconfig.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(systemconfig.FieldUpdatedBy, field.TypeUUID)
	}
	_node = &SystemConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
