// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/predicate"
	"github.com/coby/colight/apps/backend/ent/talentprofile"
)

// TalentProfileDelete is the builder for deleting a TalentProfile entity.
type TalentProfileDelete struct {
	config
	hooks    []Hook
	mutation *TalentProfileMutation
}

// Where appends a list predicates to the TalentProfileDelete builder.
func (_d *TalentProfileDelete) Where(ps ...predicate.TalentProfile) *TalentProfileDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TalentProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TalentProfileDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TalentProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(talentprofile.Table, sqlgraph.NewFieldSpec(talentprofile.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TalentProfileDeleteOne is the builder for deleting a single TalentProfile entity.
type TalentProfileDeleteOne struct {
	_d *TalentProfileDelete
}

// Where appends a list predicates to the TalentProfileDelete builder.
func (_d *TalentProfileDeleteOne) Where(ps ...predicate.TalentProfile) *TalentProfileDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TalentProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{talentprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TalentProfileDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
