// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coby/colight/apps/backend/ent/aicallerror"
	"github.com/coby/colight/apps/backend/ent/usagelog"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// UsageLog is the model entity for the UsageLog schema.
type UsageLog struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// References user_profiles(id)
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Feature name: experience, analysis, question_analysis, draft, review
	Feature string `json:"feature,omitempty"`
	// Additional context (e.g. cover_letter_id)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// AI provider: gemini, groq
	Provider *string `json:"provider,omitempty"`
	// AI model name used
	Model *string `json:"model,omitempty"`
	// Input token count
	InputTokens int `json:"input_tokens,omitempty"`
	// Output token count
	OutputTokens int `json:"output_tokens,omitempty"`
	// Total token count
	TotalTokens int `json:"total_tokens,omitempty"`
	// Estimated cost in KRW
	EstimatedCostKrw *float64 `json:"estimated_cost_krw,omitempty"`
	// API call latency in milliseconds
	LatencyMs *int `json:"latency_ms,omitempty"`
	// Call status: success, error
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageLogQuery when eager-loading is set.
	Edges        UsageLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageLogEdges holds the relations/edges for other nodes in the graph.
type UsageLogEdges struct {
	// User holds the value of the user edge.
	User *UserProfile `json:"user,omitempty"`
	// ErrorDetail holds the value of the error_detail edge.
	ErrorDetail *AICallError `json:"error_detail,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) UserOrErr() (*UserProfile, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: userprofile.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ErrorDetailOrErr returns the ErrorDetail value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) ErrorDetailOrErr() (*AICallError, error) {
	if e.ErrorDetail != nil {
		return e.ErrorDetail, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: aicallerror.Label}
	}
	return nil, &NotLoadedError{edge: "error_detail"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldMetadata:
			values[i] = new([]byte)
		case usagelog.FieldEstimatedCostKrw:
			values[i] = new(sql.NullFloat64)
		case usagelog.FieldInputTokens, usagelog.FieldOutputTokens, usagelog.FieldTotalTokens, usagelog.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case usagelog.FieldFeature, usagelog.FieldProvider, usagelog.FieldModel, usagelog.FieldStatus:
			values[i] = new(sql.NullString)
		case usagelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case usagelog.FieldID, usagelog.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLog fields.
func (_m *UsageLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case usagelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagelog.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case usagelog.FieldFeature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature", values[i])
			} else if value.Valid {
				_m.Feature = value.String
			}
		case usagelog.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case usagelog.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = new(string)
				*_m.Provider = value.String
			}
		case usagelog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case usagelog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case usagelog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case usagelog.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = int(value.Int64)
			}
		case usagelog.FieldEstimatedCostKrw:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost_krw", values[i])
			} else if value.Valid {
				_m.EstimatedCostKrw = new(float64)
				*_m.EstimatedCostKrw = value.Float64
			}
		case usagelog.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = new(int)
				*_m.LatencyMs = int(value.Int64)
			}
		case usagelog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLog.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UsageLog entity.
func (_m *UsageLog) QueryUser() *UserProfileQuery {
	return NewUsageLogClient(_m.config).QueryUser(_m)
}

// QueryErrorDetail queries the "error_detail" edge of the UsageLog entity.
func (_m *UsageLog) QueryErrorDetail() *AICallErrorQuery {
	return NewUsageLogClient(_m.config).QueryErrorDetail(_m)
}

// Update returns a builder for updating this UsageLog.
// Note that you need to call UsageLog.Unwrap() before calling this method if this UsageLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLog) Update() *UsageLogUpdateOne {
	return NewUsageLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLog) Unwrap() *UsageLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLog) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("feature=")
	builder.WriteString(_m.Feature)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.Provider; v != nil {
		builder.WriteString("provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	if v := _m.EstimatedCostKrw; v != nil {
		builder.WriteString("estimated_cost_krw=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LatencyMs; v != nil {
		builder.WriteString("latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogs is a parsable slice of UsageLog.
type UsageLogs []*UsageLog
