// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coby/colight/apps/backend/ent/application"
	"github.com/coby/colight/apps/backend/ent/coachingsession"
	"github.com/coby/colight/apps/backend/ent/companyanalysis"
	"github.com/coby/colight/apps/backend/ent/coverletter"
	"github.com/coby/colight/apps/backend/ent/experience"
	"github.com/coby/colight/apps/backend/ent/experienceusage"
	"github.com/coby/colight/apps/backend/ent/userprofile"
	"github.com/google/uuid"
)

// UserProfileCreate is the builder for creating a UserProfile entity.
type UserProfileCreate struct {
	config
	mutation *UserProfileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserProfileCreate) SetCreatedAt(v time.Time) *UserProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableCreatedAt(v *time.Time) *UserProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserProfileCreate) SetUpdatedAt(v time.Time) *UserProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableUpdatedAt(v *time.Time) *UserProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserProfileCreate) SetUserID(v uuid.UUID) *UserProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *UserProfileCreate) SetNickname(v string) *UserProfileCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableNickname(v *string) *UserProfileCreate {
	if v != nil {
		_c.SetNickname(*v)
	}
	return _c
}

// SetTargetJob sets the "target_job" field.
func (_c *UserProfileCreate) SetTargetJob(v string) *UserProfileCreate {
	_c.mutation.SetTargetJob(v)
	return _c
}

// SetNillableTargetJob sets the "target_job" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableTargetJob(v *string) *UserProfileCreate {
	if v != nil {
		_c.SetTargetJob(*v)
	}
	return _c
}

// SetTargetIndustry sets the "target_industry" field.
func (_c *UserProfileCreate) SetTargetIndustry(v string) *UserProfileCreate {
	_c.mutation.SetTargetIndustry(v)
	return _c
}

// SetNillableTargetIndustry sets the "target_industry" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableTargetIndustry(v *string) *UserProfileCreate {
	if v != nil {
		_c.SetTargetIndustry(*v)
	}
	return _c
}

// SetEducationLevel sets the "education_level" field.
func (_c *UserProfileCreate) SetEducationLevel(v string) *UserProfileCreate {
	_c.mutation.SetEducationLevel(v)
	return _c
}

// SetNillableEducationLevel sets the "education_level" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableEducationLevel(v *string) *UserProfileCreate {
	if v != nil {
		_c.SetEducationLevel(*v)
	}
	return _c
}

// SetGraduationYear sets the "graduation_year" field.
func (_c *UserProfileCreate) SetGraduationYear(v int) *UserProfileCreate {
	_c.mutation.SetGraduationYear(v)
	return _c
}

// SetNillableGraduationYear sets the "graduation_year" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableGraduationYear(v *int) *UserProfileCreate {
	if v != nil {
		_c.SetGraduationYear(*v)
	}
	return _c
}

// SetExperienceYears sets the "experience_years" field.
func (_c *UserProfileCreate) SetExperienceYears(v int) *UserProfileCreate {
	_c.mutation.SetExperienceYears(v)
	return _c
}

// SetNillableExperienceYears sets the "experience_years" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableExperienceYears(v *int) *UserProfileCreate {
	if v != nil {
		_c.SetExperienceYears(*v)
	}
	return _c
}

// SetOnboardingCompleted sets the "onboarding_completed" field.
func (_c *UserProfileCreate) SetOnboardingCompleted(v bool) *UserProfileCreate {
	_c.mutation.SetOnboardingCompleted(v)
	return _c
}

// SetNillableOnboardingCompleted sets the "onboarding_completed" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableOnboardingCompleted(v *bool) *UserProfileCreate {
	if v != nil {
		_c.SetOnboardingCompleted(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserProfileCreate) SetID(v uuid.UUID) *UserProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableID(v *uuid.UUID) *UserProfileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddExperienceIDs adds the "experiences" edge to the Experience entity by IDs.
func (_c *UserProfileCreate) AddExperienceIDs(ids ...uuid.UUID) *UserProfileCreate {
	_c.mutation.AddExperienceIDs(ids...)
	return _c
}

// AddExperiences adds the "experiences" edges to the Experience entity.
func (_c *UserProfileCreate) AddExperiences(v ...*Experience) *UserProfileCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExperienceIDs(ids...)
}

// AddApplicationIDs adds the "applications" edge to the Application entity by IDs.
func (_c *UserProfileCreate) AddApplicationIDs(ids ...uuid.UUID) *UserProfileCreate {
	_c.mutation.AddApplicationIDs(ids...)
	return _c
}

// AddApplications adds the "applications" edges to the Application entity.
func (_c *UserProfileCreate) AddApplications(v ...*Application) *UserProfileCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddApplicationIDs(ids...)
}

// AddCompanyAnalysisIDs adds the "company_analyses" edge to the CompanyAnalysis entity by IDs.
func (_c *UserProfileCreate) AddCompanyAnalysisIDs(ids ...uuid.UUID) *UserProfileCreate {
	_c.mutation.AddCompanyAnalysisIDs(ids...)
	return _c
}

// AddCompanyAnalyses adds the "company_analyses" edges to the CompanyAnalysis entity.
func (_c *UserProfileCreate) AddCompanyAnalyses(v ...*CompanyAnalysis) *UserProfileCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompanyAnalysisIDs(ids...)
}

// AddCoverLetterIDs adds the "cover_letters" edge to the CoverLetter entity by IDs.
func (_c *UserProfileCreate) AddCoverLetterIDs(ids ...uuid.UUID) *UserProfileCreate {
	_c.mutation.AddCoverLetterIDs(ids...)
	return _c
}

// AddCoverLetters adds the "cover_letters" edges to the CoverLetter entity.
func (_c *UserProfileCreate) AddCoverLetters(v ...*CoverLetter) *UserProfileCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCoverLetterIDs(ids...)
}

// AddCoachingSessionIDs adds the "coaching_sessions" edge to the CoachingSession entity by IDs.
func (_c *UserProfileCreate) AddCoachingSessionIDs(ids ...uuid.UUID) *UserProfileCreate {
	_c.mutation.AddCoachingSessionIDs(ids...)
	return _c
}

// AddCoachingSessions adds the "coaching_sessions" edges to the CoachingSession entity.
func (_c *UserProfileCreate) AddCoachingSessions(v ...*CoachingSession) *UserProfileCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCoachingSessionIDs(ids...)
}

// AddExperienceUsageIDs adds the "experience_usages" edge to the ExperienceUsage entity by IDs.
func (_c *UserProfileCreate) AddExperienceUsageIDs(ids ...uuid.UUID) *UserProfileCreate {
	_c.mutation.AddExperienceUsageIDs(ids...)
	return _c
}

// AddExperienceUsages adds the "experience_usages" edges to the ExperienceUsage entity.
func (_c *UserProfileCreate) AddExperienceUsages(v ...*ExperienceUsage) *UserProfileCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExperienceUsageIDs(ids...)
}

// Mutation returns the UserProfileMutation object of the builder.
func (_c *UserProfileCreate) Mutation() *UserProfileMutation {
	return _c.mutation
}

// Save creates the UserProfile in the database.
func (_c *UserProfileCreate) Save(ctx context.Context) (*UserProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserProfileCreate) SaveX(ctx context.Context) *UserProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ExperienceYears(); !ok {
		v := userprofile.DefaultExperienceYears
		_c.mutation.SetExperienceYears(v)
	}
	if _, ok := _c.mutation.OnboardingCompleted(); !ok {
		v := userprofile.DefaultOnboardingCompleted
		_c.mutation.SetOnboardingCompleted(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userprofile.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserProfile.user_id"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := userprofile.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "UserProfile.nickname": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetJob(); ok {
		if err := userprofile.TargetJobValidator(v); err != nil {
			return &ValidationError{Name: "target_job", err: fmt.Errorf(`ent: validator failed for field "UserProfile.target_job": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TargetIndustry(); ok {
		if err := userprofile.TargetIndustryValidator(v); err != nil {
			return &ValidationError{Name: "target_industry", err: fmt.Errorf(`ent: validator failed for field "UserProfile.target_industry": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EducationLevel(); ok {
		if err := userprofile.EducationLevelValidator(v); err != nil {
			return &ValidationError{Name: "education_level", err: fmt.Errorf(`ent: validator failed for field "UserProfile.education_level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExperienceYears(); !ok {
		return &ValidationError{Name: "experience_years", err: errors.New(`ent: missing required field "UserProfile.experience_years"`)}
	}
	if _, ok := _c.mutation.OnboardingCompleted(); !ok {
		return &ValidationError{Name: "onboarding_completed", err: errors.New(`ent: missing required field "UserProfile.onboarding_completed"`)}
	}
	return nil
}

func (_c *UserProfileCreate) sqlSave(ctx context.Context) (*UserProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserProfileCreate) createSpec() (*UserProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &UserProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userprofile.Table, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userprofile.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(userprofile.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.TargetJob(); ok {
		_spec.SetField(userprofile.FieldTargetJob, field.TypeString, value)
		_node.TargetJob = value
	}
	if value, ok := _c.mutation.TargetIndustry(); ok {
		_spec.SetField(userprofile.FieldTargetIndustry, field.TypeString, value)
		_node.TargetIndustry = value
	}
	if value, ok := _c.mutation.EducationLevel(); ok {
		_spec.SetField(userprofile.FieldEducationLevel, field.TypeString, value)
		_node.EducationLevel = value
	}
	if value, ok := _c.mutation.GraduationYear(); ok {
		_spec.SetField(userprofile.FieldGraduationYear, field.TypeInt, value)
		_node.GraduationYear = &value
	}
	if value, ok := _c.mutation.ExperienceYears(); ok {
		_spec.SetField(userprofile.FieldExperienceYears, field.TypeInt, value)
		_node.ExperienceYears = value
	}
	if value, ok := _c.mutation.OnboardingCompleted(); ok {
		_spec.SetField(userprofile.FieldOnboardingCompleted, field.TypeBool, value)
		_node.OnboardingCompleted = value
	}
	if nodes := _c.mutation.ExperiencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.ExperiencesTable,
			Columns: []string{userprofile.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApplicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.ApplicationsTable,
			Columns: []string{userprofile.ApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompanyAnalysesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.CompanyAnalysesTable,
			Columns: []string{userprofile.CompanyAnalysesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(companyanalysis.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CoverLettersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.CoverLettersTable,
			Columns: []string{userprofile.CoverLettersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coverletter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CoachingSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.CoachingSessionsTable,
			Columns: []string{userprofile.CoachingSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coachingsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExperienceUsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.ExperienceUsagesTable,
			Columns: []string{userprofile.ExperienceUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experienceusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserProfileCreateBulk is the builder for creating many UserProfile entities in bulk.
type UserProfileCreateBulk struct {
	config
	err      error
	builders []*UserProfileCreate
}

// Save creates the UserProfile entities in the database.
func (_c *UserProfileCreateBulk) Save(ctx context.Context) ([]*UserProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserProfileCreateBulk) SaveX(ctx context.Context) []*UserProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
