// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminAuditLog is the predicate function for adminauditlog builders.
type AdminAuditLog func(*sql.Selector)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// CoachingSession is the predicate function for coachingsession builders.
type CoachingSession func(*sql.Selector)

// CompanyAnalysis is the predicate function for companyanalysis builders.
type CompanyAnalysis func(*sql.Selector)

// CompanyAnalysisCache is the predicate function for companyanalysiscache builders.
type CompanyAnalysisCache func(*sql.Selector)

// CoverLetter is the predicate function for coverletter builders.
type CoverLetter func(*sql.Selector)

// CoverLetterVersion is the predicate function for coverletterversion builders.
type CoverLetterVersion func(*sql.Selector)

// DeletionRequest is the predicate function for deletionrequest builders.
type DeletionRequest func(*sql.Selector)

// Experience is the predicate function for experience builders.
type Experience func(*sql.Selector)

// ExperienceTag is the predicate function for experiencetag builders.
type ExperienceTag func(*sql.Selector)

// ExperienceUsage is the predicate function for experienceusage builders.
type ExperienceUsage func(*sql.Selector)

// ExperienceWeapon is the predicate function for experienceweapon builders.
type ExperienceWeapon func(*sql.Selector)

// Feedback is the predicate function for feedback builders.
type Feedback func(*sql.Selector)

// PromptTemplate is the predicate function for prompttemplate builders.
type PromptTemplate func(*sql.Selector)

// QuestionPattern is the predicate function for questionpattern builders.
type QuestionPattern func(*sql.Selector)

// SystemConfig is the predicate function for systemconfig builders.
type SystemConfig func(*sql.Selector)

// TalentProfile is the predicate function for talentprofile builders.
type TalentProfile func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)

// WeaponCategory is the predicate function for weaponcategory builders.
type WeaponCategory func(*sql.Selector)
